"use strict";
const M=FMZ19Model,F=FMZ19Fixtures,R=FMZ19Review,C=FMZ19Copy,D=FMZ19Data,$=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
let lang=0,model=M.create(F.base()),review=null,index=-1,actor='member',selected='syn19-recovery-5',flash='';
const t=k=>C.get(k,lang),why=k=>C.reason(k,lang),tr=(...x)=>x[lang],number=(n,d=1)=>n%d===0?String(n/d):n+' / '+d,date=x=>new Date(x).toISOString().slice(0,10);
const button=(id,k,disabled=false,primary=false)=>'<button id="'+id+'"'+(disabled?' disabled':'')+(primary?' class="primary"':'')+'>'+esc(t(k))+'</button>';
function run(action,data={}){review=null;const r=model.command(model.event(action,data,actor));flash=r.ok?(r.reason==='success'?'':why(r.reason)):why(r.reason);render();}
function restoreTarget(s){return s.history.filter(x=>x.version!==s.active.version&&s.input.rule?.allowedRestore.includes(x.option)&&s.input.agenda.allowedTimes.includes(x.at)&&D.options.some(o=>o.id===x.option&&o.requiresReportedRecovery===s.input.reportedRecovery)).at(-1)?.version||null;}
function showScenario(i){index=i;review=R.run(R.scenarios[i].id);model=review.model;actor='member';selected='syn19-recovery-5';flash='';render();$('scenario-title').scrollIntoView({block:'start'});}
function factsHTML(s){return s.facts.map(x=>'<div class="fact" data-metric="'+x.metric+'"><h3>'+esc(t(x.metric))+'</h3><div class="numbers">'+[['previous',x.previous.sum,x.previous.divisor],['current',x.current.sum,x.current.divisor],['delta',x.delta.numerator,x.delta.divisor]].map(([k,n,d])=>'<div><span>'+t(k)+'</span><strong class="'+k+'">'+number(n,d)+'</strong></div>').join('')+'</div><details><summary>'+t('source')+'</summary><p class="sub">'+x.refs.map(y=>esc(y.id)+' v'+y.version+' ('+date(y.day)+')').join(' / ')+'</p><p>'+esc(x.unit)+'; '+t('previous')+': '+x.previous.sum+' / 3; '+t('current')+': '+x.current.sum+' / 3</p></details></div>').join('');}
function trainingHTML(p){if(p.training.sessions){const catalog=JSON.parse(p.training.source);return p.training.sessions[0].exercises.map(e=>'<li>'+esc(catalog.exercises.find(x=>x.id===e.exercise).label[lang])+': '+e.sets+' x '+e.reps+'; RIR '+(e.rir??'-')+' / RPE '+(e.rpe??'-')+'</li>').join('');}return p.training.exercises.map(e=>'<li>'+esc(e.labels[['nl','en','de'][lang]])+': '+e.sets.length+' x '+e.sets[0].reps.min+'; '+e.sets[0].load.value+' '+e.sets[0].load.unit+'</li>').join('');}
function renderReview(){
 $('test-title').textContent=t('tests');$('start').textContent=t('start');
 $('scenario-buttons').innerHTML=R.scenarios.map((c,i)=>'<button id="test-'+c.id+'" data-scenario="'+i+'" aria-pressed="'+(!!review&&i===index)+'">'+(i+1)+'. '+esc(c.title[lang])+'</button>').join('');
 $('previous').textContent=t('back');$('next').textContent=t('next');$('previous').disabled=index<=0;$('next').disabled=index>=15||index<0;
 $('step').textContent=index<0?'':t('step')+' '+(index+1)+' '+t('of')+' 16';
 $('scenario-title').textContent=review?review.spec.title[lang]:t('manual');
 $('expectation').textContent=review?t('why')+': '+why(review.spec.id==='atomic'?'atomic_fault':review.spec.reason):'';
 const verdict=$('verdict');verdict.removeAttribute('data-result');verdict.textContent=t('manual');
 if(review){const s=model.view(),visible=$('state').dataset.state===s.status&&$('versions').dataset.count===String(s.history.length)&&$('signal-list').dataset.count===String(s.cards.length)&&$('reason').textContent===why(s.reason)&&s.facts.every(x=>{const e=document.querySelector('.fact[data-metric="'+x.metric+'"]');return e&&e.querySelector('.current').textContent===number(x.current.sum,3)&&e.querySelector('.delta').textContent===number(x.delta.numerator,3);});const pass=R.assess(review).pass&&visible;verdict.dataset.result=pass?'pass':'fail';verdict.textContent=pass?t('pass'):t('fail');}
}
function render(){
 const s=model.view(),f=s.input,p=f.plan,locked=s.revoked||!f.consent||s.clock>=f.sources.expires;
 document.documentElement.lang=['nl','en','de'][lang];$('title').textContent=t('title');$('notice').textContent=t('notice');
 $('language-label').textContent=tr('Taal','Language','Sprache');$('theme-label').textContent=tr('Thema','Theme','Thema');$('theme').options[0].textContent=tr('Licht','Light','Hell');$('theme').options[1].textContent=tr('Donker','Dark','Dunkel');
 $('reset').textContent=t('reset');$('route').value=f.route;$('route').options[0].textContent='B - '+tr('zonder trainer','without trainer','ohne Trainer');$('route').options[1].textContent='A - '+tr('met trainer','with trainer','mit Trainer');
 $('actor-caption').textContent=t('actor');$('actor-label').hidden=f.route!=='A';$('actor').innerHTML='<option value="member">'+t('member')+'</option><option value="trainer">'+t('trainer')+'</option>';$('actor').value=actor;
 $('agenda').innerHTML='<h2>'+t('agenda')+'</h2><p class="sub">'+tr('Vaste synthetische klok','Fixed synthetic clock','Feste synthetische Uhr')+': '+date(D.clock)+' | '+esc(p.id)+' v'+p.version+'</p><div class="grid"><div class="summary"><h3>'+t('training')+'</h3><strong>'+f.agenda.nextTraining.date+' / '+f.agenda.nextTraining.at+'</strong><ul id="training-items">'+trainingHTML(p)+'</ul><p class="sub">'+esc(p.origin.training)+'</p></div><div class="summary"><h3>'+t('checkin')+'</h3><strong>'+M.nextCheckin(s).date+' / '+M.nextCheckin(s).at+' UTC'+'</strong><p>'+t(s.active.option)+' / '+s.active.at+' / v'+s.active.version+'</p><p>'+t('nutrition')+': '+esc(p.nutrition.catalogId)+' v'+p.nutrition.catalogVersion+'</p><p>'+t('unchangedPlan')+'</p></div></div><details><summary>'+t('plans')+'</summary><p class="sub">'+esc(p.origin.nutrition)+'</p><ul>'+p.nutrition.meals.map(m=>'<li>'+esc(m.name[lang])+' / '+m.moment+'</li>').join('')+'</ul><a href="'+(f.route==='B'?'../combined-plan-demo/':'../bounded-adjustments-demo/')+'" target="_blank" rel="noopener">'+t('editPlan')+'</a><p class="sub">'+tr('Aparte geheugensimulatie: bewerkingen worden niet automatisch tussen demos gedeeld.','Separate memory simulation: edits are not automatically shared between demos.','Separate Speichersimulation: Aenderungen werden nicht automatisch zwischen Demos geteilt.')+'</p></details>';
 const row=f.rows.find(x=>x.id===selected)||f.rows.at(-1);selected=row.id;
 $('registration').innerHTML='<h2>'+t('register')+'</h2><p>'+tr('Nog te registreren check-in','Check-in awaiting a record','Noch einzutragender Check-in')+': '+f.agenda.checkin.date+' / '+f.agenda.checkin.at+' UTC</p><form id="record-form" class="register-form"><label>'+t('metric')+'<select id="record">'+f.rows.map(x=>'<option value="'+x.id+'"'+(x.id===selected?' selected':'')+'>'+date(x.day)+' / '+t(x.metric)+' / v'+x.version+'</option>').join('')+'</select></label><label>'+t('value')+'<input id="value" type="number" step="1" min="'+D.metrics[row.metric].min+'" max="'+D.metrics[row.metric].max+'" value="'+(row.value??'')+'"'+(locked||row.value===null?' disabled':'')+'></label><label class="check"><input id="missing" type="checkbox"'+(row.value===null?' checked':'')+(locked?' disabled':'')+'>'+t('missing')+'</label><button id="save-record" class="primary"'+(locked||actor!=='member'?' disabled':'')+'>'+t('save')+'</button></form><div class="actions">'+button('arrive','arrive',locked||actor!=='member')+button('complete','complete',locked||!!s.completion||actor!=='member')+'</div>'+(s.completion?'<p id="completion">'+t('completed')+' / '+esc(s.completion.record.id)+' v'+s.completion.record.version+'</p>':'')+'<details><summary>'+tr('Alle 12 bronregistraties','All 12 source records','Alle 12 Quelleintraege')+'</summary><table class="table"><thead><tr><th>'+t('metric')+'</th><th>'+t('value')+'</th><th>'+t('version')+'</th></tr></thead><tbody>'+f.rows.map(x=>'<tr><td>'+date(x.day)+'<br>'+t(x.metric)+'</td><td>'+esc(x.value===null?t('missing'):x.value)+' '+esc(x.unit)+'</td><td>v'+x.version+'</td></tr>').join('')+'</tbody></table></details>';
 const pending=!!s.proposal&&['member_pending','trainer_pending','confirmed','approved'].includes(s.status);
 $('result').innerHTML='<h2>'+t('facts')+'</h2><strong id="state" class="status" data-state="'+s.status+'">'+t(s.status==='facts'?'factsOnly':s.status)+'</strong><p id="reason">'+why(s.reason)+'</p><p id="flash" role="alert">'+esc(flash)+'</p>'+factsHTML(s)+'<p class="sub">'+t('noNorm')+'</p><div id="signal-list" data-count="'+s.cards.length+'">'+s.cards.map(c=>'<article class="signal" data-state="'+c.state+'"><h3>'+t('signal')+' / '+c.sourceRevision+'</h3><p>'+why(c.reason)+'</p><p class="sub">'+esc(c.id)+' / '+tr('bronrevisie','source revision','Quellrevision')+' '+c.sourceRevision+' / '+(c.state==='superseded'?tr('Vervallen door nieuwe bron of status','Superseded by a new source or status','Durch neue Quelle oder Status ersetzt'):c.state==='reviewed'?tr('Beoordeeld','Reviewed','Geprueft'):t('pending'))+'</p></article>').join('')+'</div>'+(pending?'<div id="proposal"><h3>'+t('option')+'</h3><p><strong>'+t(s.proposal.option)+' / '+s.proposal.at+'</strong></p><p>'+t('classification')+'</p><p class="sub">'+t('source')+': '+esc(f.rule.id)+' v'+f.rule.version+' / '+esc(D.options.find(x=>x.id===s.proposal.option).origin)+'</p><p>'+t('unchangedPlan')+'</p><div class="toolbar"><label>'+t('edit')+'<select id="time"><option>08:00</option><option>20:00</option></select></label>'+button('edit-time','edit',actor!=='member')+'</div></div>':'')+(s.status==='applied'?'<div class="toolbar"><label>'+t('edit')+'<select id="time"><option>08:00</option><option>20:00</option></select></label>'+button('edit-time','edit',actor!=='member')+'</div>'+(!restoreTarget(s)?'<p>'+why('restore_unavailable')+'</p>':''):'')+'<div class="actions">'+(s.status==='member_pending'?button('accept','accept',actor!=='member',true):'')+(s.status==='trainer_pending'?button('approve','approve',actor!=='trainer',true)+button('block','block',actor!=='trainer'):'')+(['confirmed','approved'].includes(s.status)?button('apply','apply',actor!=='member',true):'')+(pending?button('reject','reject',actor!=='member'):'')+(s.status==='applied'?button('restore','restore',actor!=='member'||!restoreTarget(s)):'')+'</div><div class="actions">'+button('revoke','revoke',locked||actor!=='member')+button('expire','expire',locked||actor!=='member')+button('plan-changed','planChanged',locked||actor!=='member')+'</div>';
 if($('time'))$('time').value=['08:00','20:00'].includes(s.proposal.at)?s.proposal.at:'08:00';
 $('history').innerHTML='<h2>'+t('history')+'</h2><p id="record-history">'+tr('Bewaarde registratieversies','Preserved record versions','Bewahrte Eintragsversionen')+': '+s.recordsHistory.length+'</p><div id="versions" class="versions" data-count="'+s.history.length+'">'+s.history.map(x=>'<div class="version"><strong>v'+x.version+'</strong><p>'+t(x.option)+' / '+x.at+'</p>'+(x.restores?'<p>'+t('restore')+': v'+x.restores+'</p>':'')+'</div>').join('')+'</div><details><summary>'+t('audit')+'</summary><ol id="audit">'+s.audit.map(x=>'<li>'+esc(x.id)+' / '+esc(x.actor)+' / '+esc(x.action)+' / v'+x.from+' - v'+x.to+' / '+new Date(x.at).toISOString()+'</li>').join('')+'</ol></details>';
 renderReview();
}
document.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b||b.disabled)return;
 if(b.dataset.scenario!==undefined)return showScenario(Number(b.dataset.scenario));
 if(b.id==='start')return showScenario(0);if(b.id==='previous')return showScenario(index-1);if(b.id==='next')return showScenario(index+1);
 if(b.id==='reset'){model=M.create(F.base($('route').value));review=null;index=-1;actor='member';flash='';return render();}
 if(b.id==='arrive'){const x=model.view().input.rows.at(-1);return run('record',{id:x.id,version:x.version,value:6});}
 if(b.id==='edit-time')return run('edit',{at:$('time').value});
 if(b.id==='restore')return run('restore',{version:restoreTarget(model.view())});
 if(b.id==='plan-changed')return run('plan_changed');
 if(['accept','approve','apply','reject','block','complete','revoke','expire'].includes(b.id))return run(b.id);
});
document.addEventListener('change',e=>{
 if(e.target.id==='language'){lang=['nl','en','de'].indexOf(e.target.value);render();}
 if(e.target.id==='theme')document.body.dataset.theme=e.target.value;
 if(e.target.id==='route'){model=M.create(F.base(e.target.value));review=null;index=-1;actor='member';flash='';render();}
 if(e.target.id==='actor'){actor=e.target.value;render();}
 if(e.target.id==='record'){selected=e.target.value;render();}
 if(e.target.id==='missing'){$('value').disabled=e.target.checked;if(!e.target.checked&&$('value').value==='')$('value').value='6';}
});
document.addEventListener('submit',e=>{if(e.target.id!=='record-form')return;e.preventDefault();const s=model.view(),x=s.input.rows.find(x=>x.id===selected),v=$('value').value;run('record',{id:x.id,version:x.version,value:$('missing').checked?null:v===''?NaN:Number(v)});});
render();
