"use strict";
const M=FMZ17Model,F=FMZ17Fixtures,R=FMZ17Review,L=FMZ17Copy,C=FMZ17Catalog;
let model=M.create(F.base),review=null,selected=-1,lastActivation=null,feedback=null;
const $=id=>document.getElementById(id),lang=()=>['nl','en','de'].indexOf($('language').value),w=k=>L.words[k][lang()],esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function n(v){const sign=v<0?'-':'';v=Math.abs(v);return sign+Math.floor(v/1000)+(v%1000?'.'+String(v%1000).padStart(3,'0').replace(/0+$/,''):'');}
function parseMilli(t){if(!/^-?\d+(\.\d{1,3})?$/.test(t))return 'invalid';const negative=t.startsWith('-'),parts=t.replace('-','').split('.');return String((negative?-1:1)*(Number(parts[0])*1000+Number((parts[1]||'').padEnd(3,'0'))));}
function textValue(x,c){if(x===null)return '-';if(Array.isArray(x))return x.length?x.map(v=>textValue(v,c)).join(', '):'0';if(typeof x==='object')return x.unit?x.value+' '+x.unit:x.id?x.id+'@'+x.version:JSON.stringify(x);const food=c.foods.find(f=>f.id===x||f.aliases.includes(x));return food?food.name[lang()]:L.values[x]?.[lang()]||String(x);}
function option(value,label,current){return '<option value="'+esc(value)+'"'+(value===current?' selected':'')+'>'+esc(label)+'</option>';}
function action(id,label,disabled=false){return '<button id="'+id+'"'+(disabled?' disabled':'')+'>'+esc(w(label))+'</button>';}
function totals(values,prefix,label){return '<h3>'+esc(w(label))+'</h3><div class="totals">'+M.keys.map(k=>'<div>'+esc(w(k))+'<strong id="'+prefix+k+'">'+n(values[k])+'</strong></div>').join('')+'</div>';}
function planView(p,s,prefix,editable){if(!p)return '<p>'+esc(w('none'))+'</p>';const hits=R.forbiddenHits(p,JSON.parse(p.intake),JSON.parse(p.source)),c=JSON.parse(p.source);let html='<p>'+esc(w('source'))+': '+esc(p.catalogId+'@'+p.catalogVersion+' | '+p.ruleId+'@'+p.ruleVersion)+' | '+esc(p.target.id+'@'+p.target.version)+'</p><p>'+esc(w('reason'))+': '+esc(c.rules[0].reason[lang()])+'</p><p>'+esc(L.labels.weight[lang()])+': '+p.bodyWeight.value+' '+esc(p.bodyWeight.unit)+' | '+esc(w('grams'))+'</p>';
 html+=totals(p.target.totals,prefix+'target-','planned')+totals(p.total,prefix+'total-','calculated')+totals(p.difference,prefix+'diff-','difference');
 html+='<p>'+esc(w('allergens'))+': <strong id="'+prefix+'allergens">'+hits.allergens+'</strong></p><p>'+esc(w('excludedHits'))+': <strong id="'+prefix+'excluded">'+hits.excluded+'</strong></p><p class="muted">'+esc(w('concept'))+'</p>';
 p.meals.forEach((m,j)=>{html+='<article class="meal"><h3>'+esc(m.moment+' | '+m.name[lang()])+'</h3>';
  if(editable)html+='<div class="meal-controls"><select id="moment-'+j+'" aria-label="'+esc(w('moment'))+'">'+s.intake.moments.value.map(x=>option(x,x,m.moment)).join('')+'</select><button id="move-'+j+'">'+esc(w('edit'))+'</button><select id="recipe-'+j+'" aria-label="'+esc(w('replace'))+'">'+m.alternatives.map(a=>option(a.id,c.recipes.find(r=>r.id===a.id).name[lang()],m.recipe)).join('')+'</select><button id="replace-'+j+'">'+esc(w('replace'))+'</button></div>';
  html+='<p>'+esc(w('planned'))+': '+m.sharePercent+'% | '+M.keys.map(k=>esc(w(k))+': '+n(m.planned[k])).join(' | ')+'</p><p>'+esc(w('calculated'))+': '+M.keys.map(k=>esc(w(k))+': '+n(m.totals[k])).join(' | ')+'</p>';
  m.items.forEach((x,k)=>{const id=j+'-'+k;html+='<div class="food"><strong>'+esc(x.name[lang()])+'</strong><p class="muted">'+esc(x.food+'@'+x.foodVersion)+'</p>';
   if(editable)html+='<div class="food-edit"><label>'+esc(w('alternatives'))+'<select class="food-select" id="food-'+id+'">'+x.alternatives.map(a=>option(a.id,c.foods.find(f=>f.id===a.id).name[lang()],x.food)).join('')+'</select></label><label>'+esc(w('grams'))+'<input id="grams-'+id+'" type="number" inputmode="decimal" value="'+x.grams+'" min="'+x.bounds.min+'" max="'+x.bounds.max+'" step="'+x.bounds.step+'"></label><button id="edit-'+id+'">'+esc(w('edit'))+'</button></div>';
   else html+='<p>'+x.grams+' g</p>';
   html+='<p>'+esc(w('range'))+': '+x.bounds.min+'-'+x.bounds.max+' g / '+x.bounds.step+' g</p><p class="math">'+M.keys.map(key=>esc(w(key))+': '+n(x.per100[key])+' x '+x.grams+' / 100 = '+n(x.nutrients[key])).join('<br>')+'</p><p class="alternatives">'+esc(w('alternatives'))+': '+x.alternatives.map(a=>esc(c.foods.find(f=>f.id===a.id).name[lang()])).join(', ')+'</p></div>';
  });html+='<p class="math">'+M.keys.map(k=>m.items.map(x=>n(x.nutrients[k])).join(' + ')+' = '+n(m.totals[k])+' '+esc(w(k))).join('<br>')+'</p></article>';
 });return html;
}
function visible(){const s=model.view(),p=s.draft;return {rows:p?p.meals.flatMap((m,j)=>m.items.map((x,k)=>({meal:j,food:$('food-'+j+'-'+k).value,grams:$('grams-'+j+'-'+k).value}))):[],alternatives:p?p.meals.flatMap((m,j)=>m.items.map((x,k)=>[...$('food-'+j+'-'+k).options].map(x=>x.value))):[],recipes:p?p.meals.map((m,j)=>[...$('recipe-'+j).options].map(x=>x.value)):[],totals:p?M.keys.map(k=>parseMilli($('total-'+k).textContent)):[],difference:p?M.keys.map(k=>parseMilli($('diff-'+k).textContent)):[],hits:p?{allergens:Number($('allergens').textContent),excluded:Number($('excluded').textContent),checked:R.forbiddenHits(p,s.intake,s.catalog).checked}:null,versions:$('versions').dataset.versions,confirm:!!$('confirm'),activate:!!$('activate')};}
function renderReview(){const v=$('verdict');v.removeAttribute('data-result');if(!review){v.textContent=w('changed');$('checks').replaceChildren();return;}const verdict=R.assess(review,model.view(),visible());v.textContent=w(verdict.pass?'pass':'fail');v.dataset.result=verdict.pass?'pass':'fail';$('checks').innerHTML=verdict.checks.map(c=>'<li>'+esc(c.key)+': '+(c.pass?'PASS':'FAIL')+'</li>').join('');}
function edited(){review=null;renderReview();}
function execute(action,data={},event){edited();const e=event||model.event(action,data),r=model.command(e);if(action==='activate'&&r.ok)lastActivation=e;feedback=r;render();}
function scenario(index){selected=index;review=R.run(R.scenarios[index].id);model=review.model;lastActivation=null;feedback=null;render();$('review').scrollIntoView({block:'start',behavior:'auto'});}
function preferenceForm(s){const c=s.catalog;let html='';
 for(const [key,options]of [['favorites',c.foods.map(f=>f.id)],['excluded',c.foods.map(f=>f.id)],['allergies',['peanut','soy','milk','gluten']]]){const current=s.intake[key].status==='known'?s.intake[key].value:[];html+='<label>'+esc(L.labels[key][lang()])+'<select id="pref-'+key+'" multiple size="4">'+options.map(x=>'<option value="'+x+'"'+(current.includes(x)?' selected':'')+'>'+esc(textValue(x,c))+'</option>').join('')+'</select></label>';}
 for(const [key,options]of [['diet',['plant','any']],['meals',[2,3,4]],['maxRecipes',[1,2,3,4]],['prepMinutes',[0,10,20,30]],['units',['metric','imperial']]])html+='<label>'+esc(L.labels[key][lang()])+'<select id="pref-'+key+'">'+options.map(x=>option(String(x),textValue(x,c),String(s.intake[key].value))).join('')+'</select></label>';
 html+='<label>'+esc(L.labels.moments[lang()])+'<input id="pref-moments" value="'+esc((s.intake.moments.value||[]).join(', '))+'"></label>';
 $('preference-form').innerHTML=html;$('save').disabled=s.revoked||s.intake.consent.value!==true;
 $('save').onclick=()=>{const i=model.view().intake;for(const k of ['favorites','excluded','allergies'])i[k]=F.known([...$('pref-'+k).selectedOptions].map(x=>x.value));for(const k of ['diet','units'])i[k]=F.known($('pref-'+k).value);for(const k of ['meals','maxRecipes','prepMinutes'])i[k]=F.known(Number($('pref-'+k).value));i.moments=F.known($('pref-moments').value.split(',').map(x=>x.trim()));execute('intake',i);};
}
function render(){const s=model.view();document.documentElement.lang=$('language').value;document.body.dataset.theme=$('theme').value;
 for(const [id,key]of Object.entries({title:'title',scope:'scope','test-heading':'tests',start:'start',previous:'previous',next:'next','expected-heading':'expected','checks-heading':'checks','intake-heading':'intake','preferences-heading':'preferences',save:'save',concept:'concept','before-heading':'before','proposal-heading':'proposal','active-heading':'active','audit-heading':'audit',safety:'safety'}))$(id).textContent=w(key);
 for(const opt of $('theme').options)opt.textContent=w(opt.value);
 $('scenario-buttons').innerHTML=R.scenarios.map((x,j)=>'<button id="test-'+x.id+'" aria-pressed="'+(selected===j)+'">'+(j+1)+'. '+esc(x.title[lang()])+'</button>').join('');R.scenarios.forEach((x,j)=>$('test-'+x.id).onclick=()=>scenario(j));
 $('step').textContent=selected<0?'':w('step')+' '+(selected+1)+' '+w('of')+' 20';$('scenario-title').textContent=selected<0?w('intro'):R.scenarios[selected].title[lang()];$('expected').textContent=selected<0?'':R.scenarios[selected].expected[lang()];$('previous').disabled=selected<=0;$('next').disabled=selected<0||selected===19;
 $('intake').innerHTML=C.fields.map(k=>'<dt>'+esc(L.labels[k][lang()])+'</dt><dd>'+esc(w(s.intake[k]?.status||'missing'))+' | '+esc(textValue(s.intake[k]?.value??null,s.catalog))+'</dd>').join('');preferenceForm(s);
 $('sources').textContent=w('source')+': '+s.catalog.id+'@'+s.catalog.version+' | '+s.catalog.rules.map(r=>r.id+'@'+r.version).join(', ');
 $('actions').innerHTML=action('build','build')+(s.status==='pending'?action('confirm','confirm'):'')+(s.status==='confirmed'?action('activate','activate'):'')+(['pending','confirmed'].includes(s.status)?action('reject','reject'):'')+(s.active?action('duplicate','duplicate'):'')+(s.history.length>1?action('restore','restore'):'')+action('source','sourceChange')+action('revoke','revoke')+action('reset','reset');
 $('build').onclick=()=>execute('build');if($('confirm'))$('confirm').onclick=()=>execute('confirm');if($('activate'))$('activate').onclick=()=>execute('activate');if($('reject'))$('reject').onclick=()=>execute('reject');if($('duplicate'))$('duplicate').onclick=()=>execute('activate',{},lastActivation||undefined);if($('restore'))$('restore').onclick=()=>execute('restore',{version:1});
 $('source').onclick=()=>{const c=model.view().catalog;c.version++;execute('source',c);};$('revoke').onclick=()=>execute('revoke');$('reset').onclick=()=>{model=M.create(F.base);selected=-1;review=null;feedback=null;lastActivation=null;render();};
 $('feedback').textContent=feedback?(feedback.reason==='success'?w('success'):(feedback.ok?'':w('blocked')+': ')+L.error(feedback.reason,lang())):'';
 $('before').hidden=!review?.before;$('before-plan').innerHTML=review?.before?planView(review.before,s,'before-',false):'';
 $('proposal').innerHTML=planView(s.draft,s,'',true);$('active-plan').innerHTML=planView(s.active?.plan,s,'active-',false);
 $('versions').dataset.versions=s.history.map(h=>h.version).join(' / ')||'-';$('versions').textContent=w('history')+': '+$('versions').dataset.versions;
 $('audit').innerHTML=s.audit.map(e=>'<li>'+esc(e.action+' | '+e.from+' -> '+e.to+' | '+e.id+' | '+e.status+' | '+new Date(e.at).toISOString())+'</li>').join('');
 if(s.draft)s.draft.meals.forEach((m,j)=>{$('move-'+j).onclick=()=>execute('edit',{kind:'moment',meal:j,moment:$('moment-'+j).value});$('replace-'+j).onclick=()=>execute('edit',{kind:'recipe',meal:j,recipe:$('recipe-'+j).value});m.items.forEach((x,k)=>$('edit-'+j+'-'+k).onclick=()=>execute('edit',{kind:'item',meal:j,index:k,food:$('food-'+j+'-'+k).value,grams:$('grams-'+j+'-'+k).value===''?null:Number($('grams-'+j+'-'+k).value)}));});
 document.querySelectorAll('#proposal input,#proposal select,#preference-form input,#preference-form select').forEach(e=>e.addEventListener('input',edited));renderReview();
}
$('language').onchange=render;$('theme').onchange=render;$('start').onclick=()=>scenario(0);$('previous').onclick=()=>scenario(selected-1);$('next').onclick=()=>scenario(selected+1);render();
