(function(root){"use strict";const M=typeof module==='object'?require('./model.js'):root.FMZ17Model,F=typeof module==='object'?require('./fixtures.js'):root.FMZ17Fixtures,copy=F.copy,same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const rows=[
['complete',['Volledige voedingsintake','Complete nutrition intake','Vollstaendige Ernaehrungsangaben'],['Concept op basis van het bestaande doel; nog niet actief.','Draft uses the existing target; not active yet.','Entwurf nutzt das bestehende Ziel; noch nicht aktiv.']],
['missing',['Ontbrekend bronveld','Missing source field','Fehlendes Quellfeld'],['Activiteitsinformatie ontbreekt: geen voorstel en geen schatting.','Activity is missing: no proposal or estimate.','Aktivitaet fehlt: kein Vorschlag und keine Schaetzung.']],
['target',['Bestaand doel gebruiken','Use existing target','Bestehendes Ziel nutzen'],['Doel blijft 1800 kcal. Berekend plan: 1725 kcal. Verschil: -75 kcal.','Target remains 1800 kcal. Calculated plan: 1725 kcal. Difference: -75 kcal.','Ziel bleibt 1800 kcal. Berechneter Plan: 1725 kcal. Differenz: -75 kcal.']],
['no_rule',['Geen goedgekeurde doelregel','No approved target rule','Keine freigegebene Zielregel'],['Zonder bestaand doel of goedgekeurde berekeningsregel komt er geen voorstel.','No proposal without an existing target or approved calculation rule.','Kein Vorschlag ohne bestehendes Ziel oder freigegebene Berechnungsregel.']],
['allergy',['Allergie: nul keer aanwezig','Allergy: zero occurrences','Allergie: null Vorkommen'],['Pinda en soja komen nul keer voor, ook in alternatieven en recepten.','Peanut and soy occur zero times, including alternatives and recipes.','Erdnuss und Soja kommen nullmal vor, auch in Alternativen und Rezepten.']],
['excluded',['Uitsluiting en andere namen','Exclusion and other names','Ausschluss und andere Namen'],['Groundnut verwijst naar pinda: ook de pindakom en vervanging zijn uitgesloten.','Groundnut means peanut: peanut bowl and substitution are excluded too.','Groundnut bedeutet Erdnuss: Erdnussschale und Ersatz sind ebenfalls ausgeschlossen.']],
['favorite',['Favoriet product','Favorite food','Lieblingsprodukt'],['Linzen zijn gekozen uit de veilige bronopties.','Lentils selected from safe source options.','Linsen aus zulaessigen Quelloptionen gewaehlt.']],
['meal',['Maaltijd vervangen','Replace meal','Mahlzeit ersetzen'],['De eerste bonenkom wordt een linzenkom; totalen worden opnieuw berekend.','First bean bowl becomes a lentil bowl; totals are recalculated.','Erste Bohnenschale wird Linsenschale; Summen werden neu berechnet.']],
['portion',['Portie binnen de grens','Portion within bounds','Portion innerhalb der Grenzen'],['Rijst gaat van 200 naar 225 bron-grammen; geen verborgen afronding.','Rice changes from 200 to 225 source grams; no hidden rounding.','Reis von 200 auf 225 Quellgramm; keine versteckte Rundung.']],
['outside',['Portie buiten de grens','Portion outside bounds','Portion ausserhalb der Grenzen'],['450 gram wordt geweigerd. Het vorige concept blijft gelijk.','450 grams refused. Previous draft stays identical.','450 Gramm abgelehnt. Vorheriger Entwurf bleibt gleich.']],
['totals',['Maaltijd- en dagtotalen','Meal and day totals','Mahlzeit- und Tagessummen'],['Drie maaltijden van 575 kcal zijn exact 1725 kcal; doelverschil blijft zichtbaar.','Three meals of 575 kcal equal exactly 1725 kcal; target difference remains visible.','Drei Mahlzeiten mit 575 kcal ergeben exakt 1725 kcal; Zieldifferenz bleibt sichtbar.']],
['nutrient',['Ontbrekende voedingswaarde','Missing nutrient value','Fehlender Naehrwert'],['Ontbrekend eiwitgehalte wordt niet verzonnen: geen voorstel.','Missing protein value is not invented: no proposal.','Fehlendes Protein wird nicht erfunden: kein Vorschlag.']],
['conflict',['Conflicterende bronversie','Conflicting source version','Widerspruechliche Quellversion'],['Recept en product verwijzen naar verschillende versies: geblokkeerd.','Recipe and food reference different versions: blocked.','Rezept und Produkt verweisen auf unterschiedliche Versionen: blockiert.']],
['source',['Broncorrectie voor activering','Source correction before activation','Quellkorrektur vor Aktivierung'],['Oude bevestiging vervalt; opnieuw beoordelen en bevestigen.','Old confirmation expires; reassess and confirm again.','Alte Bestaetigung verfaellt; neu bewerten und bestaetigen.']],
['duplicate',['Dubbel bevestigen en activeren','Duplicate confirmation and activation','Doppelt bestaetigen und aktivieren'],['Herhaling maakt geen extra versie: er blijft versie 1.','Repeating creates no extra version: version 1 remains.','Wiederholung erzeugt keine weitere Version: Version 1 bleibt.']],
['restore',['Vorige versie terugzetten','Restore previous version','Vorherige Version wiederherstellen'],['Versies 1 en 2 blijven; herstel wordt versie 3 na aparte bevestiging en activering.','Versions 1 and 2 remain; restore becomes version 3 after separate confirmation and activation.','Versionen 1 und 2 bleiben; Wiederherstellung wird Version 3 nach getrennten Schritten.']],
['medical',['Medische beperking of klacht','Medical restriction or complaint','Medizinische Einschraenkung oder Beschwerde'],['Persoonlijke voedingsaanpassing geblokkeerd. Passende deskundige beoordeling blijft nodig.','Personal nutrition adjustment blocked. Appropriate professional review remains necessary.','Persoenliche Ernaehrungsanpassung blockiert. Geeignete fachliche Pruefung bleibt erforderlich.']],
['consent',['Toestemming ingetrokken','Consent withdrawn','Einwilligung widerrufen'],['Geen verdere verwerking of nieuw voorstel; bestaande historie blijft behouden.','No further processing or new proposal; existing history is preserved.','Keine weitere Verarbeitung oder neuer Vorschlag; bisherige Historie bleibt erhalten.']],
['units',['Brongewicht en gramporties','Source weight and gram portions','Quellgewicht und Grammportionen'],['165 lb blijft 165 lb; porties blijven bron-grammen. Geen conversie of herinterpretatie.','165 lb stays 165 lb; portions stay source grams. No conversion or reinterpretation.','165 lb bleiben 165 lb; Portionen bleiben Quellgramm. Keine Umrechnung oder Umdeutung.']],
['language',['Taal en thema','Language and theme','Sprache und Darstellung'],['NL, EN en DE tonen dezelfde bronwaarden; licht en donker veranderen geen plan.','NL, EN and DE show the same source values; light and dark do not change the plan.','NL, EN und DE zeigen dieselben Quellwerte; Hell/Dunkel aendert keinen Plan.']]
];const scenarios=rows.map(([id,title,expected])=>({id,title,expected}));
function fixture(id){const f=copy(F.base);if(id==='missing')f.intake.activity=F.missing();if(id==='no_rule')f.intake.target=F.na();if(id==='allergy')f.intake.allergies=F.known(['peanut','soy']);if(id==='excluded')f.intake.excluded=F.known(['groundnut']);if(id==='favorite')f.intake.favorites=F.known(['linzen']);if(id==='nutrient')delete f.catalog.foods[0].nutrients.protein;if(id==='conflict')f.catalog.foods[0].version=2;if(id==='medical')f.intake.health=F.known('medical_restriction');if(id==='units'){f.intake.weight=F.known({value:165,unit:'lb'});f.intake.height=F.known({value:69,unit:'in'});f.intake.units=F.known('imperial');}return f;}
function itemEdit(m,extra={}){const x=m.view().draft.meals[0].items[0];return {kind:'item',meal:0,index:0,food:x.food,grams:x.grams,...extra};}
function forbiddenHits(plan,intake,c){if(!plan)return null;const allergy=intake.allergies.status==='known'?intake.allergies.value:[],excluded=intake.excluded.status==='known'?intake.excluded.value.map(x=>M.resolve(c,x)):[];const ids=[];for(const m of plan.meals){ids.push(...m.items.map(x=>x.food),...m.items.flatMap(x=>x.alternatives.map(a=>a.id)));for(const alt of m.alternatives){const r=c.recipes.find(r=>r.id===alt.id);ids.push(...r.items.map(x=>x.food));}}return {allergens:ids.reduce((n,id)=>n+c.foods.find(f=>f.id===id).allergens.concat(c.foods.find(f=>f.id===id).mayContain).filter(x=>allergy.includes(x)).length,0),excluded:ids.filter(x=>excluded.includes(x)).length,checked:ids.length};}
function run(id,factory=M.create){const spec=scenarios.find(x=>x.id===id);if(!spec)throw Error('scenario');let model=factory(fixture(id)),before=null,failed=false;const events=[],checks=[];const add=(key,pass)=>checks.push({key,pass:pass===true});
 function act(action,data={},expected='success',e){const old=model.view(),event=e||model.event(action,data),r=model.command(event);events.push({action,expected,reason:r.reason,ok:r.ok,before:old,after:model.view()});add(action,r.reason===expected&&r.ok===['success','idempotent'].includes(expected));if(!r.ok)add('no_partial_write',same(old,model.view()));if(r.reason!==expected)throw Error('unexpected');return event;}
 try{
  const blocked={missing:'missing:activity',no_rule:'no_target_rule',nutrient:'nutrient',conflict:'source_conflict',medical:'medical'};
  if(blocked[id])act('build',{},blocked[id]);else{
   act('build');before=copy(model.view().draft);
   if(id==='meal')act('edit',{kind:'recipe',meal:0,recipe:'lentil_bowl'});
   if(id==='portion')act('edit',itemEdit(model,{grams:225}));
   if(id==='outside')act('edit',itemEdit(model,{grams:450}),'portion');
   if(id==='excluded'){act('edit',itemEdit(model,{index:1,food:'peanut',grams:150}),'excluded');act('edit',{kind:'recipe',meal:0,recipe:'peanut_bowl'},'recipe');}
   if(id==='source'){act('confirm');const e=model.event('activate'),c=model.view().catalog;c.version++;act('source',c);act('activate',{},'version_conflict',e);}
   if(id==='duplicate'){const confirm=act('confirm');act('confirm',{},'idempotent',confirm);act('confirm',{},'idempotent');const e=act('activate');act('activate',{},'idempotent',e);act('activate',{},'version_conflict');}
   if(id==='restore'){act('confirm');act('activate');act('build');act('edit',itemEdit(model,{grams:225}));act('confirm');act('activate');const old=copy(model.view().history);act('restore',{version:1});act('activate',{},'version_conflict');act('confirm');act('activate');add('old_versions',same(model.view().history.slice(0,2),old)&&same(model.view().active.plan,old[0].plan));}
   if(id==='consent'){act('confirm');act('activate');const h=copy(model.view().history);act('revoke');act('build',{},'consent');act('intake',copy(F.base.intake),'consent');add('history',same(h,model.view().history));}
   if(id==='units'){const old=copy(model.view().intake.weight);const i=model.view().intake;i.units=F.known('metric');act('intake',i);act('build');add('unit_preserved',same(old,model.view().intake.weight)&&model.view().draft.meals.every(m=>m.items.every(x=>x.unit==='g')));}
  }
  const s=model.view(),p=s.draft;
  if(p){M.validatePlan(p,s.intake,s.catalog,s.clock);const hits=forbiddenHits(p,s.intake,s.catalog);add('allergen_and_exclusion_zero',hits.allergens===0&&hits.excluded===0);for(const k of M.keys){add('sum_'+k,p.total[k]===p.meals.reduce((sum,m)=>sum+m.totals[k],0));add('planned_'+k,p.target.totals[k]===p.meals.reduce((sum,m)=>sum+m.planned[k],0));}if(['complete','target','totals'].includes(id))add('explicit_difference',p.total.energy===1725000&&p.difference.energy===-75000);if(id==='favorite')add('favorite',p.meals.every(m=>m.items.some(x=>x.food==='lentils')));}
  add('no_auto',s.automatic_actions_allowed===false&&s.medical_clearance===false&&s.external_calls===0);add('version',s.version===(id==='restore'?3:['duplicate','consent'].includes(id)?1:0));
 }catch(_){failed=true;add('complete',false);}
 return {id,spec,model,before,events,checks,failed,expectedState:model.view()};
}
const counts={complete:1,missing:1,target:1,no_rule:1,allergy:1,excluded:3,favorite:1,meal:2,portion:2,outside:2,totals:1,nutrient:1,conflict:1,source:4,duplicate:7,restore:11,medical:1,consent:6,units:3,language:1};
function facts(s){const p=s.draft;return {rows:(p?.meals||[]).flatMap((m,j)=>m.items.map(x=>({meal:j,food:x.food,grams:String(x.grams)}))),alternatives:(p?.meals||[]).flatMap(m=>m.items.map(x=>x.alternatives.map(a=>a.id))),recipes:(p?.meals||[]).map(m=>m.alternatives.map(a=>a.id)),totals:p?M.keys.map(k=>String(p.total[k])):[],difference:p?M.keys.map(k=>String(p.difference[k])):[],hits:p?forbiddenHits(p,s.intake,s.catalog):null,versions:s.history.map(h=>h.version).join(' / ')||'-',confirm:s.status==='pending',activate:s.status==='confirmed'};}
function assess(r,s,visible){const checks=copy(r.checks);checks.push({key:'complete',pass:!r.failed&&r.events.length===counts[r.id]&&r.checks.length>=r.events.length+2},{key:'current',pass:same(s,r.expectedState)});if(visible)checks.push({key:'visible',pass:same(visible,facts(s))});return {pass:checks.every(x=>x.pass),checks};}
const api={scenarios,fixture,run,assess,facts,itemEdit,forbiddenHits};if(typeof module==='object')module.exports=api;else root.FMZ17Review=api;
})(globalThis);
