"use strict";
const A=require("./adapter.cjs"),M=require("../../training-review-demo/model.js"),copy=require("../../training-review-demo/copy.js");
function generate(){
 const result=[];
 for(const locale of ["nl","en","de"])for(const scenario of ["normal","step_off_grid","restore","member_reject","trainer_block"]){
  const seed=A.seed(scenario==="step_off_grid"?scenario:"normal",locale),c=copy[locale],m=M.create(seed);
  const number=x=>String(x).replace(".",locale==="en"?".":",");
  const messages=[c.demo,seed.goal.labels[locale]];
  for(const r of seed.rows)messages.push(r.labels[locale]+": "+c.oldPlan+" "+r.current.sets+" x "+r.current.reps+" @ "+number(r.current.load.value)+" "+r.current.load.unit+
   "; "+c.next+" "+r.next.sets+" x "+r.next.reps+" @ "+number(r.next.load.value)+" "+r.next.load.unit+". "+c[r.reason]);
  if(seed.gate){messages.push(c[seed.gate]);for(const r of seed.w2)messages.push(r.exercise+": "+c.step+" "+number(r.step)+" "+r.unit+"; "+c.weights+" "+r.available.map(number).join(", ")+" "+r.unit+".");}
  const actions=scenario==="restore"?["member_accept","trainer_approve","apply","restore","member_accept","trainer_approve","apply"]:
    scenario==="member_reject"?["member_reject"]:scenario==="trainer_block"?["member_accept","trainer_block"]:[];
  for(const action of actions){const actor=action.startsWith("member")||action==="restore"?"member":"trainer";const out=m.command(m.event(action,actor,"cmd-example-"+m.view().revision,action==="restore"?3:null));if(!out.ok)throw Error(out.reason);}
  const keys={approved:"approved_notice",applied:"applied_notice",restore:"restore_notice",blocked:"blocked_notice",rejected:"rejected_notice"};
  const notifications=m.view().notifications.map(n=>({recipient:n.recipient,message:c[keys[n.key]||n.key]+(n.reason?" "+c[n.reason]:"")}));
  result.push({locale,scenario,messages,notifications,audit:m.view().audit,active_version:m.view().active.revision,previous_versions:m.view().history.map(p=>p.revision),
   automatic_actions_allowed:false,physical_advice_authorized:false,source_kind:"synthetic_only"});
 }
 return result;
}
module.exports={generate};
if(require.main===module){
 const fs=require("node:fs"),examples=generate();
 fs.writeFileSync("docs/PHASE6E7_EXAMPLES.json",JSON.stringify(examples,null,2)+"\n");
 let md="# Package 6E-7 Executable Concept Examples\n\nGenerated by _offline/phase6e7/examples.cjs. Synthetic only; no expert approval.\n\n";
 for(const e of examples)md+="## "+e.locale.toUpperCase()+" / "+e.scenario+"\n\n"+e.messages.map(m=>"- "+m).join("\n")+"\n\n"+e.notifications.map(n=>"- "+n.recipient+": "+n.message).join("\n")+"\n\nActive v"+e.active_version+"; saved: "+e.previous_versions.join(", ")+".\n\n";
 fs.writeFileSync("docs/PHASE6E7_EXAMPLES.md",md);console.log(JSON.stringify({examples:examples.length}));
}
