"use strict";
const fs=require('node:fs'),p=require('node:path'),a=require('node:assert/strict'),{chromium}=require('C:/Users/Fitme/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {server,allowed}=require('./serve.cjs'),R=require('../../recovery-checkin-demo/review.js'),C=require('../../recovery-checkin-demo/copy.js'),out=process.argv[2],remote=process.argv.includes('--published');
const result={remote,source_sha256:Object.fromEntries(fs.readdirSync('recovery-checkin-demo').map(f=>[f,require('node:crypto').createHash('sha256').update(fs.readFileSync('recovery-checkin-demo/'+f)).digest('hex')])),checks:[],layouts:[],errors:[],requests:[],screenshots:[]},check=(name,pass)=>{result.checks.push({name,pass:!!pass});a(pass,name);},stamp=Date.now();
(async()=>{let serverInstance,browser;try{
 let base='https://yourizorge.github.io/fitmetzorge-staging';if(!remote){serverInstance=server();await new Promise(r=>serverInstance.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+serverInstance.address().port;}
 browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 async function open(width,height=900){const ctx=await browser.newContext({viewport:{width,height},serviceWorkers:'block'});
  await ctx.addInitScript(()=>{window.__writes=[];for(const k of ['localStorage','sessionStorage','indexedDB'])Object.defineProperty(window,k,{get(){window.__writes.push(k);throw Error('storage_blocked');}});Object.defineProperty(document,'cookie',{get(){return '';},set(){window.__writes.push('cookie');}});});
  await ctx.route('**/*',r=>{const q=r.request(),u=new URL(q.url()),prefix=remote?'/fitmetzorge-staging':'',ok=q.method()==='GET'&&u.origin===new URL(base).origin&&allowed.includes(u.pathname.slice(prefix.length));result.requests.push({path:u.pathname,allowed:ok});if(!ok){result.errors.push('egress');return r.abort();}return r.continue();});
  const page=await ctx.newPage();page.on('pageerror',e=>result.errors.push(e.message));await page.goto(base+'/recovery-checkin-demo/index.html',{waitUntil:'networkidle'});return {page,ctx};
 }
 async function layout(page,key){const bad=await page.evaluate(()=>[...document.querySelectorAll('main *,header *')].filter(e=>{const r=e.getBoundingClientRect();return e.tagName!=='OPTION'&&r.width&&r.height&&(r.left<-.5||r.right>innerWidth+.5);}).map(e=>e.tagName+'.'+e.className));result.layouts.push({key,overflow:bad});check(key+' no overflow',bad.length===0);check(key+' unique IDs',await page.locator('[id]').evaluateAll(es=>new Set(es.map(e=>e.id)).size===es.length));}
 for(const width of [320,390,768,1280])for(const language of ['nl','en','de'])for(const theme of ['light','dark']){
  const {page,ctx}=await open(width),key=width+'-'+language+'-'+theme,l=['nl','en','de'].indexOf(language);await page.selectOption('#language',language);await page.selectOption('#theme',theme);
  check(key+' sixteen cases',await page.locator('#scenario-buttons button').count()===16);check(key+' brand',await page.locator('header img').evaluate(e=>e.naturalWidth>0));check(key+' touch targets',await page.locator('#scenario-buttons button').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().height>=64)));check(key+' Route B has no trainer selector',await page.locator('#actor-label').isHidden());
  for(const c of R.scenarios){
   await page.click('#test-'+c.id);check(key+' '+c.id+' pass',await page.locator('#verdict').getAttribute('data-result')==='pass');check(key+' '+c.id+' localized title',await page.locator('#scenario-title').innerText()===c.title[l]);check(key+' '+c.id+' explanation',await page.locator('#expectation').innerText().then(x=>x.includes(C.reason(c.id==='atomic'?'atomic_fault':c.reason,l))));await layout(page,key+' '+c.id);
  }
  await page.click('#test-arrival');check(key+' sleep diff',await page.locator('[data-metric=sleep] .delta').innerText()==='-90');check(key+' recovery diff',await page.locator('[data-metric=recovery] .delta').innerText()==='-2');check(key+' twelve records',await page.locator('.table tbody tr').count()===12);check(key+' separate apply',await page.locator('#apply').count()===0&&await page.locator('#versions').getAttribute('data-count')==='1');
  await page.click('#test-correction');check(key+' exact fraction',await page.locator('[data-metric=recovery] .current').innerText()==='20 / 3');check(key+' superseded notice',await page.locator('.signal[data-state=superseded]').count()===1);
  await page.click('#test-health');check(key+' facts despite safety',await page.locator('.fact').count()===2&&await page.locator('#accept,#apply').count()===0&&!(await page.locator('#arrive').isDisabled()));
  await page.click('#test-consent');check(key+' no new processing',await page.locator('#save-record').isDisabled()&&await page.locator('#arrive').isDisabled());
  if(language==='nl'&&(width===390||width===1280)){await page.click('#test-arrival');for(const [name,id]of [['agenda','agenda'],['facts','result'],['review','review']]){await page.locator('#'+id).scrollIntoViewIfNeeded();const file=p.join(out,(remote?'published':'local')+'-'+stamp+'-'+name+'-'+key+'.png');await page.screenshot({path:file});result.screenshots.push(file);}}
  check(key+' no storage',(await page.evaluate(()=>window.__writes)).length===0);await ctx.close();
 }
 const {page,ctx}=await open(390,700);
 await page.focus('#start');await page.keyboard.press('Enter');check('first previous disabled',await page.locator('#previous').isDisabled());for(let i=1;i<16;i++){await page.click('#next');check('guided '+i,await page.locator('#step').innerText()==='Stap '+(i+1)+' van 16'&&await page.locator('#verdict').getAttribute('data-result')==='pass');}check('last next disabled',await page.locator('#next').isDisabled());await page.click('#previous');check('guided previous',await page.locator('#step').innerText()==='Stap 15 van 16');
 await page.click('#test-arrival');await page.evaluate(()=>{document.querySelector('[data-metric=sleep] .delta').textContent='999';renderReview();});check('wrong displayed fact red',await page.locator('#verdict').getAttribute('data-result')==='fail');
 await page.click('#test-arrival');await page.evaluate(()=>{document.getElementById('reason').textContent='wrong';renderReview();});check('wrong reason red',await page.locator('#verdict').getAttribute('data-result')==='fail');
 for(const route of ['B','A']){
  await page.selectOption('#route',route);await page.click('#arrive');await page.click('#accept');check(route+' explicit application',await page.locator('#versions').getAttribute('data-count')==='1');
  if(route==='A'){check('member cannot approve',await page.locator('#approve').isDisabled());await page.selectOption('#actor','trainer');await page.click('#approve');check('trainer cannot apply',await page.locator('#apply').isDisabled());await page.selectOption('#actor','member');}
  await page.click('#apply');check(route+' version two',await page.locator('#versions').getAttribute('data-count')==='2');
  await page.click('#restore');check(route+' restore requires approval',await page.locator('#accept').count()===1&&await page.locator('#apply').count()===0);await page.click('#accept');if(route==='A'){await page.selectOption('#actor','trainer');await page.click('#approve');await page.selectOption('#actor','member');}await page.click('#apply');check(route+' restore version three',await page.locator('#versions').getAttribute('data-count')==='3');
 }
 await page.selectOption('#route','B');await page.click('#arrive');await page.click('#accept');
 await page.selectOption('#record','syn19-recovery-5');await page.fill('#value','8');await page.click('#save-record');check('manual correction cleared approval',await page.locator('#accept').count()===1&&await page.locator('#apply').count()===0&&await page.locator('#verdict').getAttribute('data-result')===null);check('manual correction updates fact',await page.locator('[data-metric=recovery] .current').innerText()==='20 / 3');
 await page.selectOption('#time','20:00');await page.click('#edit-time');await page.click('#accept');await page.click('#apply');check('time edit preserved',await page.locator('.version').last().innerText().then(x=>x.includes('20:00')));
 await page.click('#complete');check('completion one record',await page.locator('#completion').innerText().then(x=>x.includes('v3')));await page.click('#plan-changed');check('upstream plan edit blocks',await page.locator('#state').getAttribute('data-state')==='blocked'&&await page.locator('#apply').count()===0);
 await page.click('#revoke');check('withdraw disabled',await page.locator('#save-record').isDisabled());await layout(page,'manual');
 await page.reload({waitUntil:'networkidle'});check('refresh reset',await page.locator('#audit li').count()===0&&await page.locator('#versions').getAttribute('data-count')==='1'&&await page.locator('#value').inputValue()==='');await ctx.close();
 check('no errors or unexpected requests',result.errors.length===0);result.status='BROWSER_PASS';
 }catch(e){result.status='BROWSER_FAIL';result.failure=e.message;process.exitCode=1;}finally{if(browser)await browser.close();if(serverInstance)await new Promise(r=>serverInstance.close(r));fs.writeFileSync(p.join(out,(remote?'published':'local')+'-browser-'+Date.now()+'.json'),JSON.stringify(result,null,2),{flag:'wx'});console.log(JSON.stringify({status:result.status,checks:result.checks.length,layouts:result.layouts.length,errors:result.errors,failure:result.failure}));}
})();
