"use strict";
const fs=require('node:fs'),c=require('node:crypto'),E=require('../phase6e13/engine.cjs'),F=require('../phase6e13/fixtures.cjs'),C=require('../../coach-review-demo/catalog.js'),B=require('../../coach-review-demo/model.js'),P=require('../../combined-plan-demo/model.js'),PF=require('../../combined-plan-demo/fixtures.js'),A=require('../phase6e14/catalog.cjs');
const copy=x=>JSON.parse(JSON.stringify(x)),sha=x=>c.createHash('sha256').update(x).digest('hex'),clock=PF.base.clock,DAY=86400000,end=Math.floor(clock/DAY)*DAY,pair=P.inspect(PF.base),source=F.fixture('changes');
const paths=['_offline/phase6e13/engine.cjs','_offline/phase6e13/fixtures.cjs','coach-review-demo/catalog.js','coach-review-demo/model.js','bounded-adjustments-demo/model.js','combined-plan-demo/model.js','training-rules-demo/model.js','nutrition-rules-demo/model.js'];
const plans={B:{id:'syn19-plan-b',version:1,training:pair.training,nutrition:pair.nutrition,origin:{training:'syn16-training-rules/v1',nutrition:'syn17-food-catalog/v1',binding:'declared-synthetic-alias:syn19-member=syn16-member=syn17-member'}},A:{id:'syn19-plan-a',version:3,training:copy(A.catalogs.a_progression.before.training),nutrition:pair.nutrition,origin:{training:'accepted6e14:'+A.catalogs.a_progression.id,nutrition:'read-only-synthetic-existing-syn17-target/v1',binding:'declared-synthetic-alias:syn19-member=syn-owner=syn17-member'}}};
const options=['after_workout','daily'].map((id,i)=>{const intake=copy(C.defaults);intake.recovery=i?'low':'okay';const cadence=B.build(intake).recovery.checkins;if(cadence!==id)throw Error('frozen_cadence_mismatch');return {id,version:1,requiresReportedRecovery:intake.recovery,origin:'accepted6e8/15 recovery.checkins',source:sha(fs.readFileSync('coach-review-demo/model.js'))};});
const rows=source.bundle.rows.filter(x=>['sleep','recovery'].includes(x.metric)).map((r,i)=>({id:'syn19-'+r.metric+'-'+(i%6),version:1,subject:'syn19-member',metric:r.metric,day:end-(6-i%6)*DAY,value:r.value,unit:r.unit,method:r.method,coverage:r.coverage,quality:r.quality}));
const data={synthetic_only:true,clock,DAY,policy:copy(E.POLICY),metrics:{sleep:E.METRICS.sleep,recovery:E.METRICS.recovery},plans,options,rows,source_sha256:Object.fromEntries(paths.map(p=>[p,sha(fs.readFileSync(p))])),provenance:{original13clock:source.gate.now_ms,newClock:clock,synthetic_date_rebase:true,training_and_nutrition_expert_validated:false}};
fs.writeFileSync('recovery-checkin-demo/data.js','/* Generated fictional sources; no member data or live authority. */\n(function(r){const data='+JSON.stringify(data)+';if(typeof module==="object")module.exports=data;else r.FMZ19Data=data;})(globalThis);\n',{flag:'wx'});console.log({rows:rows.length,options:options.length,sources:paths.length});
