"use strict";
const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),c=require('node:crypto'),M=require('../../recovery-checkin-demo/model.js'),F=require('../../recovery-checkin-demo/fixtures.js'),R=require('../../recovery-checkin-demo/review.js'),C=require('../../recovery-checkin-demo/copy.js'),D=require('../../recovery-checkin-demo/data.js'),E13=require('../phase6e13/engine.cjs'),F13=require('../phase6e13/fixtures.cjs');
const copy=M.copy,send=(m,action,data={},actor='member',opt={})=>m.command(m.event(action,data,actor),opt);
const fill=m=>{const r=m.view().input.rows.at(-1);return send(m,'record',{id:r.id,version:r.version,value:6});};
const ready=route=>{const m=M.create(F.base(route));a(fill(m).ok);return m;};
const approved=route=>{const m=ready(route);a(send(m,'accept').ok);if(route==='A')a(send(m,'approve',{},'trainer').ok);return m;};
for(const spec of R.scenarios)for(let l=0;l<3;l++){
 test('scenario '+spec.id+' '+l,()=>{const r=R.run(spec.id);a(R.assess(r).pass);a(C.reason(r.spec.reason,l).length>15);a(spec.title[l].length>3);a.equal(r.model.view().external_calls,0);a.equal(r.model.view().physical_advice_authorized,false);});
 test('review rejects false status '+spec.id+' '+l,()=>{const r=R.run(spec.id),s=r.model.view();s.status='fabricated';a.equal(R.assess(r,s).pass,false);});
}
for(const [path,sha]of Object.entries(D.source_sha256))test('frozen dependency '+path,()=>a.equal(c.createHash('sha256').update(fs.readFileSync(path)).digest('hex'),sha));
test('accepted 13 calculations reused exactly',()=>{const fixture=F13.fixture('changes'),original=E13.evaluate(fixture.bundle,fixture.gate),f=F.base();f.rows.at(-1).value=6;const now=M.compare(f);for(const x of now){const old=original.calculations.find(y=>y.metric===x.metric);a(old);a.equal(x.previous.sum,old.previous.sum);a.equal(x.current.sum,old.current.sum);a.equal(x.delta.numerator,old.delta_numerator);a.equal(x.delta.divisor,old.delta_divisor);}});
test('fixed policy and explicit non-medical category',()=>{a.deepEqual(D.policy,E13.POLICY);a.deepEqual(D.metrics,{sleep:E13.METRICS.sleep,recovery:E13.METRICS.recovery});const f=F.base();f.reportedRecovery=null;const m=M.create(f);fill(m);a.equal(m.view().reason,'classification_missing');a.equal(m.view().facts.length,2);});
const rowMutations=[
 ['other person',x=>x.subject='syn-other'],['other plan',x=>x.plan='syn-other'],['stale plan',x=>x.planVersion=999],['no revision',x=>x.version=0],['fractional revision',x=>x.version=1.5],['wrong id',x=>x.id='syn19-recovery-0'],['future day',x=>x.day+=86400000],['extra row field',x=>x.private_note='forbidden'],
 ['null',x=>x.value=null],['negative',x=>x.value=-1],['fraction',x=>x.value=.5],['string',x=>x.value='450'],['undefined',x=>delete x.value],['too large',x=>x.value=1441],['wrong unit',x=>x.unit='hours'],['wrong method',x=>x.method='device'],['partial',x=>x.coverage='partial'],['disputed',x=>x.quality='disputed']];
for(const [name,mutate]of rowMutations)for(const route of ['A','B'])test('blocked source '+route+' '+name,()=>{const f=F.base(route);f.rows.at(-1).value=6;mutate(f.rows[0]);a.throws(()=>M.compare(f));});
for(const [name,mutate]of [
 ['duplicate ID',f=>f.rows[1].id=f.rows[0].id],['duplicate day',f=>f.rows[1].day=f.rows[0].day],['missing row',f=>f.rows.pop()],['extra row',f=>f.rows.push(copy(f.rows[0]))],['real scope',f=>f.synthetic_only=false],['other subject',f=>f.subject='other'],['unknown route',f=>f.route='C'],['edited plan',f=>f.plan.version++],['wrong appointment',f=>f.agenda.planVersion++],['unknown time',f=>f.agenda.allowedTimes.push('21:00')],['wrong session day',f=>f.agenda.nextTraining.day='thu'],['future source',f=>f.sources.issued=f.clock+100],['expired',f=>f.sources.expires=f.clock],['invalid expiry',f=>f.sources.expires=f.sources.issued],['missing clock',f=>delete f.clock]
])test('contract refuses '+name,()=>{const f=F.base();f.rows.at(-1).value=6;mutate(f);a.throws(()=>M.compare(f));});
test('row ordering immaterial',()=>{const f=F.base();f.rows.at(-1).value=6;const before=M.compare(f);f.rows.reverse();a.deepEqual(M.compare(f),before);});
for(const [name,mutate]of [['extra source',f=>f.sources.other=true],['extra contract',f=>f.other=true],['unbounded source',f=>f.sources.expires+=D.DAY],['old comparison',f=>{f.clock+=D.DAY;f.sources.issued+=D.DAY;f.sources.expires+=D.DAY;}],['future comparison',f=>{f.clock-=D.DAY;f.sources.issued-=D.DAY;f.sources.expires-=D.DAY;}]])test('strict source window '+name,()=>{const f=F.base();f.rows.at(-1).value=6;mutate(f);a.throws(()=>M.compare(f));});
test('sleep zero is a record, not missing or a medical finding',()=>{const f=F.base();f.rows.at(-1).value=6;f.rows[0].value=0;a.equal(M.compare(f)[0].previous.sum,900);f.rows[0].value=null;a.throws(()=>M.compare(f),/missing/);});
for(const [name,mutate]of [
 ['absent',f=>f.rule=null],['origin',f=>f.rule.origin='fake'],['other rule',f=>f.rule.id='syn19-unknown'],['new version',f=>f.rule.version=2],['expired',f=>f.rule.expires=f.clock],['future',f=>f.rule.at=f.clock+1],['revoked',f=>f.rule.status='revoked'],['other plan',f=>f.rule.plan='other'],['stale plan',f=>f.rule.planVersion=99],['option',f=>f.rule.option='weekly'],['option version',f=>f.rule.optionVersion=2],['restore rights',f=>f.rule.allowedRestore=[]],['extra rule',f=>f.rule.otherRule={}],['numeric inference forbidden',f=>f.reportedRecovery='okay']
])for(const route of ['A','B'])test('rule refuses '+route+' '+name,()=>{const f=F.base(route);mutate(f);const m=M.create(f);fill(m);a.equal(m.view().proposal,null);a.equal(m.view().active.version,1);a.equal(m.view().facts.length,2);});
for(const route of ['A','B']){
 test(route+' approval atomic apply restore independently',()=>{const m=ready(route),original=copy(m.view().input.plan);a.equal(send(m,'apply').ok,false);a(send(m,'accept').ok);a.equal(m.view().active.version,1);if(route==='A'){a.equal(send(m,'apply').ok,false);a.equal(send(m,'approve').reason,'actor');a(send(m,'approve',{},'trainer').ok);}else a.equal(send(m,'approve',{},'trainer').reason,'actor');const e=m.event('apply');a(m.command(e).ok);const first=m.view();a(m.command(e).ok);a.deepEqual(m.view(),first);a.equal(send(m,'apply').ok,false);a(send(m,'restore',{version:1}).ok);a.equal(send(m,'apply').ok,false);a(send(m,'accept').ok);if(route==='A')a(send(m,'approve',{},'trainer').ok);a(send(m,'apply').ok);a.equal(m.view().history.length,3);a.equal(m.view().active.option,'after_workout');a.deepEqual(m.view().input.plan,original);a.equal(m.view().history[0].version,1);});
 test(route+' failure rolls back whole state',()=>{const m=approved(route),before=m.view(),e=m.event('apply');a.equal(m.command(e,{fault_before_commit:true}).reason,'atomic_fault');a.deepEqual(m.view(),before);a(m.command(e).ok);a.equal(m.view().active.version,2);});
 for(const action of ['record','context','expire','revoke','rule_revoked','plan_changed','edit']){
  test(route+' stale request after '+action,()=>{const m=approved(route),e=m.event('apply');const args={record:{id:'syn19-recovery-5',version:2,value:8},context:{health:'reported_resolved'},edit:{at:'20:00'}};a(send(m,action,args[action]||{}).ok);const s=m.view();a.equal(m.command(e).ok,false);a.deepEqual(m.view(),s);a.equal(s.active.version,1);if(action==='record'||action==='edit')a.equal(s.member,false);});
 }
 test(route+' declined proposal has no partial change',()=>{const m=ready(route);a(send(m,'reject').ok);a.equal(send(m,'apply').ok,false);a.equal(m.view().active.version,1);a.equal(m.view().proposal,null);});
 for(const state of ['current','reported_resolved','unclassified','missing_context'])test(route+' safety '+state,()=>{const f=F.base(route);f.health=state;const m=M.create(f);a(fill(m).ok);a.equal(m.view().facts.length,2);a.equal(m.view().reason,'safety');a.equal(m.view().proposal,null);a(send(m,'context',{health:'none'}).ok);a.equal(m.view().reason,'safety');a(send(m,'complete').ok);a.equal(m.view().active.version,1);});
 test(route+' memory immutability',()=>{const f=F.base(route),m=M.create(f);f.consent=false;f.rows[0].value=null;a(fill(m).ok);const v=m.view();v.input.plan.version=99;v.active.version=99;a.equal(m.view().active.version,1);a.notEqual(m.view().input.plan.version,99);});
}
test('trainer block does not erase plan',()=>{const m=ready('A');send(m,'accept');a(send(m,'block',{},'trainer').ok);a.equal(m.view().active.version,1);a.equal(send(m,'apply').ok,false);});
test('wrong trainer relationship denied',()=>{const f=F.base('A');f.rule.trainer.relationshipVersion=2;const m=M.create(f);fill(m);a.equal(m.view().reason,'trainer');});
for(const [field,value]of [['subject','other'],['route','A'],['actor','admin'],['basis','wrong'],['id','unsafe']])test('request binding '+field,()=>{const m=approved('B'),before=m.view(),e=m.event('apply');e[field]=value;a.equal(m.command(e).ok,false);a.deepEqual(m.view(),before);});
test('request hash conflict preserves state',()=>{const m=approved('B'),e=m.event('apply');a(m.command(e).ok);e.action='restore';const s=m.view();a.equal(m.command(e).reason,'duplicate_conflict');a.deepEqual(m.view(),s);});
for(const action of ['record','refresh','complete'])test('no-op request ID cannot be reused for a different write '+action,()=>{const m=ready('B');if(action==='complete')send(m,'complete');const data=action==='record'?{id:'syn19-recovery-5',version:2,value:6}:{};const e=m.event(action,data);a(m.command(e).ok);const before=m.view();a.equal(m.command(e).reason,'idempotent');e.action='record';e.data={id:'syn19-recovery-5',version:2,value:8};a.equal(m.command(e).reason,'duplicate_conflict');a.deepEqual(m.view(),before);});
test('record replay and refresh do not inflate card history',()=>{const m=ready('B'),before=m.view();for(let i=0;i<10;i++){a.equal(fill(m).reason,'unchanged_record');a.equal(send(m,'refresh').reason,'already_assessed');}a.deepEqual(m.view(),before);});
test('correction archives prior record and supersedes card',()=>{const m=ready('B');send(m,'accept');send(m,'record',{id:'syn19-recovery-5',version:2,value:8});const s=m.view();a.equal(s.cards[0].state,'superseded');a.equal(s.recordsHistory[1].at(-1).value,6);a.equal(s.recordsHistory[2].at(-1).value,8);a.equal(s.facts[1].current.sum,20);a.equal(s.facts[1].delta.numerator,-4);a.equal(s.member,false);});
test('removing record clears stale conclusion, retains history',()=>{const m=ready('B');send(m,'record',{id:'syn19-recovery-5',version:2,value:null});const s=m.view();a.equal(s.facts.length,0);a.equal(s.proposal,null);a.equal(s.cards[0].state,'superseded');a.equal(s.recordsHistory.length,3);});
test('completion remains tied to original record after correction',()=>{const m=ready('B');send(m,'complete');send(m,'record',{id:'syn19-recovery-5',version:2,value:8});a.equal(m.view().completion.record.version,2);a.equal(m.view().input.rows.at(-1).version,3);});
test('revoked consent denies registration and idempotent replay',()=>{const m=ready('B'),e=m.event('accept');m.command(e);send(m,'revoke');const s=m.view();a.equal(m.command(e).reason,'consent');a.equal(fill(m).reason,'consent');a.equal(send(m,'complete').reason,'consent');a.deepEqual(m.view(),s);});
test('bounded history avoids unbounded memory',()=>{const m=ready('B');for(let i=0;i<18;i++){const x=m.view().input.rows.at(-1);a(send(m,'record',{id:x.id,version:x.version,value:i%2?6:7}).ok);}const before=m.view(),x=before.input.rows.at(-1);a.equal(send(m,'record',{id:x.id,version:x.version,value:8}).reason,'memory_limit');a.deepEqual(m.view(),before);});
for(const value of [NaN,Infinity,-Infinity,'6',undefined])test('invalid input is not converted to missing '+String(value),()=>{const m=ready('B'),s=m.view();a.equal(send(m,'record',{id:'syn19-recovery-5',version:2,value}).ok,false);a.deepEqual(m.view(),s);});
test('applied version retains complete rule and source binding',()=>{const m=approved('A');send(m,'apply');const s=m.view();a.deepEqual(s.active.binding.rule,s.input.rule);a.equal(s.active.binding.records.at(-1).version,2);send(m,'record',{id:'syn19-recovery-5',version:2,value:8});a.deepEqual(m.view().history[1],s.history[1]);a.equal(m.view().history[1].binding.records.at(-1).version,2);});
test('next appointment from active cadence only',()=>{const m=approved('B');a.deepEqual(M.nextCheckin(m.view()),{date:'2026-10-05',at:'19:00',zone:'UTC',cadenceVersion:1});send(m,'apply');a.deepEqual(M.nextCheckin(m.view()),{date:'2026-10-02',at:'08:00',zone:'UTC',cadenceVersion:2});});
test('explicit evening choice creates same-day check-in, no medical threshold',()=>{const m=ready('B');send(m,'edit',{at:'20:00'});send(m,'accept');send(m,'apply');a.equal(M.nextCheckin(m.view()).date,'2026-10-01');const s=m.view();s.clock=Date.parse('2026-10-01T20:00:00Z');a.equal(M.nextCheckin(s).date,'2026-10-02');});
for(const [k,values]of Object.entries(C.words))test('three UI languages '+k,()=>a(values.length===3&&values.every(x=>typeof x==='string'&&x.length>0)));
for(const [k,values]of Object.entries(C.reasons))test('three explanation languages '+k,()=>a(values.length===3&&values.every(x=>x.length>10)));
test('no network persistence or private imports in public modules',()=>{for(const f of fs.readdirSync('recovery-checkin-demo')){const s=fs.readFileSync('recovery-checkin-demo/'+f,'utf8');a(!/\b(fetch|XMLHttpRequest|WebSocket|localStorage|sessionStorage|indexedDB)\s*[.(]/.test(s),f);a(!/supabase\.co|service_role|sb_secret_/.test(s),f);a(!/(?:require\(|from |src=)[^\n;]*_offline\//.test(s),f);}a(fs.readFileSync('recovery-checkin-demo/index.html','utf8').includes("connect-src 'none'"));});
