"use strict";
const fs=require('node:fs'),p=require('node:path'),a=require('node:assert/strict'),{chromium}=require('C:/Users/Fitme/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {server,allowed}=require('./serve.cjs'),R=require('../../nutrition-rules-demo/review.js'),out=process.argv[2],remote=process.argv.includes('--published');
const result={remote,checks:[],layouts:[],errors:[],requests:[],screenshots:[]},check=(name,pass)=>{result.checks.push({name,pass:!!pass});a(pass,name);};
const stamp=Date.now();
(async()=>{let serverInstance,browser;try{
 let base='https://yourizorge.github.io/fitmetzorge-staging';if(!remote){serverInstance=server();await new Promise(r=>serverInstance.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+serverInstance.address().port;}
 browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 async function open(width,height=900){const ctx=await browser.newContext({viewport:{width,height},serviceWorkers:'block'});
  await ctx.addInitScript(()=>{window.__writes=[];for(const k of ['localStorage','sessionStorage','indexedDB'])Object.defineProperty(window,k,{get(){window.__writes.push(k);throw Error('storage_blocked');}});Object.defineProperty(document,'cookie',{get(){return '';},set(){window.__writes.push('cookie');}});});
  await ctx.route('**/*',r=>{const q=r.request(),u=new URL(q.url()),prefix=remote?'/fitmetzorge-staging':'',ok=q.method()==='GET'&&u.origin===new URL(base).origin&&allowed.includes(u.pathname.slice(prefix.length));result.requests.push({path:u.pathname,allowed:ok});if(!ok){result.errors.push('egress');return r.abort();}return r.continue();});
  const page=await ctx.newPage();page.on('pageerror',e=>result.errors.push(e.message));await page.goto(base+'/nutrition-rules-demo/index.html',{waitUntil:'networkidle'});return {page,ctx};
 }
 async function layout(page,key){const bad=await page.evaluate(()=>[...document.querySelectorAll('main *,header *')].filter(e=>{const r=e.getBoundingClientRect();return e.tagName!=='OPTION'&&r.width&&r.height&&(r.left<-.5||r.right>innerWidth+.5);}).map(e=>e.tagName+'.'+e.className));result.layouts.push({key,overflow:bad});check(key+' no overflow',bad.length===0);const duplicates=await page.locator('[id]').evaluateAll(es=>es.map(e=>e.id).filter((id,i,ids)=>ids.indexOf(id)!==i));check(key+' unique IDs',duplicates.length===0);}
 for(const width of [320,390,768,1280])for(const language of ['nl','en','de'])for(const theme of ['light','dark']){
  const {page,ctx}=await open(width),key=width+'-'+language+'-'+theme;await page.selectOption('#language',language);await page.selectOption('#theme',theme);
  check(key+' twenty scenarios',await page.locator('#scenario-buttons button').count()===20);check(key+' brand',await page.locator('header img').evaluate(e=>e.naturalWidth>0));check(key+' touch targets',await page.locator('#scenario-buttons button').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().height>=64)));
  for(const c of R.scenarios){await page.click('#test-'+c.id);check(key+' '+c.id+' PASS',await page.locator('#verdict').getAttribute('data-result')==='pass');check(key+' '+c.id+' title',await page.locator('#scenario-title').innerText()===c.title[['nl','en','de'].indexOf(language)]);check(key+' '+c.id+' result visible',await page.locator('#verdict').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}));await layout(page,key+' '+c.id);}
  await page.click('#test-target');check(key+' exact target difference',await page.locator('#total-energy').innerText()==='1725'&&await page.locator('#target-energy').innerText()==='1800'&&await page.locator('#diff-energy').innerText()==='-75');
  await page.click('#test-allergy');check(key+' zero allergens',await page.locator('#allergens').innerText()==='0');check(key+' no unsafe choices',await page.locator('#proposal select option').evaluateAll(es=>es.every(e=>!['peanut','tofu','peanut_bowl','tofu_bowl'].includes(e.value))));
  await page.click('#test-excluded');check(key+' zero excluded',await page.locator('#excluded').innerText()==='0');
  await page.click('#test-units');check(key+' original lb',await page.locator('#proposal').innerText().then(s=>s.includes('165 lb')));
  await page.click('#test-consent');check(key+' blocked after consent',await page.locator('#confirm,#activate').count()===0&&await page.locator('#save').isDisabled());
  if(language==='nl'&&(width===390||width===1280)){
   await page.click('#test-allergy');await page.locator('#review').scrollIntoViewIfNeeded();const f=p.join(out,(remote?'published':'local')+'-'+stamp+'-'+key+'.png');await page.screenshot({path:f});result.screenshots.push(f);
   await page.locator('#proposal').scrollIntoViewIfNeeded();const g=p.join(out,(remote?'published':'local')+'-'+stamp+'-plan-'+key+'.png');await page.screenshot({path:g});result.screenshots.push(g);
  }
  check(key+' no browser storage',(await page.evaluate(()=>window.__writes)).length===0);await ctx.close();
 }
 const {page,ctx}=await open(390,480);await page.locator('#start').focus();await page.keyboard.press('Enter');check('guided first',await page.locator('#previous').isDisabled());
 for(let i=1;i<20;i++){await page.click('#next');check('guided '+i,await page.locator('#step').innerText()==='Stap '+(i+1)+' van 20'&&await page.locator('#verdict').getAttribute('data-result')==='pass');}check('guided last',await page.locator('#next').isDisabled());await page.click('#previous');check('guided previous',await page.locator('#step').innerText()==='Stap 19 van 20');
 await page.click('#test-complete');await page.evaluate(()=>{$('total-energy').textContent='999';renderReview();});check('corrupted total red',await page.locator('#verdict').getAttribute('data-result')==='fail');
 await page.click('#test-allergy');await page.evaluate(()=>{const opt=document.createElement('option');opt.value='peanut';opt.textContent='peanut';$('food-0-1').append(opt);renderReview();});check('unsafe alternative red',await page.locator('#verdict').getAttribute('data-result')==='fail');
 await page.click('#test-complete');await page.evaluate(()=>{review.events.pop();renderReview();});check('missing proof red',await page.locator('#verdict').getAttribute('data-result')==='fail');
 await page.click('#test-complete');await page.fill('#grams-0-0','225');check('manual edit clears verdict',await page.locator('#verdict').getAttribute('data-result')===null);await page.click('#edit-0-0');check('real exact fraction',await page.locator('#total-energy').innerText()==='1757.5');
 await page.fill('#grams-0-0','450');await page.click('#edit-0-0');check('invalid unchanged',await page.locator('#grams-0-0').inputValue()==='225'&&await page.locator('#total-energy').innerText()==='1757.5');
 await page.selectOption('#food-0-0','potato');await page.click('#edit-0-0');check('food swapped',await page.locator('#food-0-0').inputValue()==='potato');
 await page.selectOption('#recipe-0','lentil_bowl');await page.click('#replace-0');check('meal swapped',await page.locator('#recipe-0').inputValue()==='lentil_bowl'&&await page.locator('#total-energy').innerText()==='1740');
 await page.selectOption('#moment-0','20:00');await page.click('#move-0');check('moment moved',await page.locator('#moment-0').inputValue()==='20:00');
 await page.locator('#confirm').focus();await page.keyboard.press('Enter');check('separate activation',await page.locator('#activate').count()===1&&await page.locator('#versions').getAttribute('data-versions')==='-');await page.click('#activate');await page.click('#duplicate');check('one version',await page.locator('#versions').getAttribute('data-versions')==='1');
 await page.click('#build');await page.click('#confirm');await page.click('#activate');await page.click('#restore');check('restore needs confirmation',await page.locator('#confirm').count()===1&&await page.locator('#activate').count()===0);await page.click('#confirm');await page.click('#activate');check('restore version3',await page.locator('#versions').getAttribute('data-versions')==='1 / 2 / 3');
 await page.click('#source');check('source invalidates',await page.locator('#proposal .food').count()===0&&await page.locator('#activate').count()===0);
 await page.click('#reset');await page.locator('#preferences summary').click();await page.selectOption('#pref-favorites',['lentils']);await page.selectOption('#pref-allergies',['peanut','soy']);await page.click('#save');await page.click('#build');check('preference new assessment',await page.locator('#food-0-1').inputValue()==='lentils'&&await page.locator('#allergens').innerText()==='0');await layout(page,'keyboard-space');
 await page.click('#revoke');await page.click('#build');check('revocation blocks',await page.locator('#confirm,#activate').count()===0&&await page.locator('#save').isDisabled());
 await page.reload({waitUntil:'networkidle'});check('refresh reset',await page.locator('#audit li').count()===0&&await page.locator('#verdict').getAttribute('data-result')===null);await ctx.close();check('no errors or extra egress',result.errors.length===0);result.status='BROWSER_PASS';
 }catch(e){result.status='BROWSER_FAIL';result.failure=e.message;process.exitCode=1;}finally{if(browser)await browser.close();if(serverInstance)await new Promise(r=>serverInstance.close(r));fs.writeFileSync(p.join(out,(remote?'published':'local')+'-browser-'+Date.now()+'.json'),JSON.stringify(result,null,2),{flag:'wx'});console.log(JSON.stringify({status:result.status,checks:result.checks.length,layouts:result.layouts.length,errors:result.errors,failure:result.failure}));}
})();
