export const copy={
  "nl": {
    "title": "Trainerbronnen",
    "badge": "6E-10 · Synthetische stagingdemo",
    "limit": "Uitsluitend fictieve schema's. Geen live AI of echte trainingswijziging.",
    "login": "Inloggen",
    "email": "Testaccount",
    "password": "Wachtwoord",
    "logout": "Uitloggen",
    "refresh": "Vernieuwen",
    "language": "Taal",
    "theme": "Thema",
    "light": "Licht",
    "dark": "Donker",
    "system": "Systeem",
    "busy": "Bezig...",
    "retry": "Dezelfde aanvraag opnieuw proberen",
    "error": "Niet uitgevoerd. Vernieuw de toestand en controleer de bron en het testvenster.",
    "network": "Geen antwoord ontvangen. De server kan de actie al hebben uitgevoerd. Probeer dezelfde aanvraag opnieuw.",
    "signin": "Gebruik het bestaande wachtwoord van het gekozen synthetische account.",
    "inactive": "Geen actief testvenster. Er zijn geen schema- of brongegevens beschikbaar.",
    "role": "Rol",
    "a_member": "Route A · Lid",
    "a_trainer": "Route A · Trainer",
    "b_member": "Route B · AI-only lid",
    "window": "Testvenster",
    "ends": "Toegang tot",
    "manage": "Vensterbeheer",
    "prepare": "Nieuw venster voorbereiden",
    "hours": "Geldigheid in uren",
    "scenario": "Scenario",
    "activate": "Venster activeren",
    "revoke": "Venster intrekken",
    "cleanup": "Fixtures opruimen",
    "prepared": "Voorbereid",
    "active": "Actief",
    "expired": "Verlopen",
    "revoked": "Ingetrokken",
    "cleaned": "Opgeruimd",
    "open": "Openen",
    "sources": "Trainerbronnen",
    "newsource": "Nieuwe bronversie",
    "append": "Bronversie vastleggen",
    "withdraw": "Actuele bron intrekken",
    "note": "Toelichting trainer",
    "minSessions": "Vereiste vergelijkbare sessies",
    "comparable": "Vergelijkbare schemaversies",
    "validfrom": "Geldig vanaf",
    "validuntil": "Geldig tot",
    "rules": "Expliciete trainerregels",
    "selector": "Koppeling",
    "exercise": "Oefening",
    "type": "Oefeningstype",
    "unit": "Eenheid",
    "minreps": "Min. reps",
    "maxreps": "Max. reps",
    "repstep": "Repsstap",
    "resetreps": "Reps na gewichtsstap",
    "weightstep": "Gewichtsstap",
    "weights": "Toegestane gewichten",
    "minsets": "Min. sets",
    "maxsets": "Max. sets",
    "priority": "Voorrang (leeg = geen)",
    "required": "Verplicht",
    "min": "Min.",
    "max": "Max.",
    "addRule": "Typeregel toevoegen",
    "proposals": "Voorstellen",
    "propose": "Nieuw voorstel maken",
    "member_pending": "Wacht op lid",
    "member_accepted": "Wacht op trainer",
    "approved": "Goedgekeurd, nog toepassen",
    "applied": "Toegepast",
    "rejected": "Afgewezen",
    "blocked": "Geblokkeerd",
    "stale": "Verouderd: nieuwe bron of schemaversie. Nieuwe goedkeuringen nodig.",
    "member_accept": "Als lid accepteren",
    "member_reject": "Als lid afwijzen",
    "trainer_approve": "Als trainer goedkeuren",
    "trainer_reject": "Als trainer afwijzen",
    "trainer_block": "Als trainer blokkeren",
    "apply": "Wijziging toepassen",
    "base": "Huidig plandoel",
    "observed": "Geregistreerd",
    "next": "Voorstel",
    "reason": "Reden",
    "reps": "Alle geregistreerde sets halen het plandoel binnen de trainergrenzen. De vastgelegde repsstap past.",
    "weight": "Het vastgelegde maximum aantal reps is geregistreerd. De volledige trainerstap past bij de toegestane gewichten.",
    "hold": "De registraties voldoen niet aan alle vastgelegde progressievoorwaarden. Het doel blijft gelijk.",
    "history": "Schemageschiedenis",
    "restore": "Terugzetten voorstellen",
    "original": "Oorspronkelijke bron",
    "source": "Bron",
    "version": "Versie",
    "audit": "Auditgeschiedenis",
    "nothing": "Nog geen voorstel.",
    "emptySource": "Nog geen geldige trainerbron. Er wordt geen wijziging verzonnen.",
    "b": "Route B heeft geen gekoppelde trainer en krijgt geen toegang tot trainerbronnen, A-voorstellen of A-schema's. In 6E-10 zijn geen nieuwe autonome platformregels beschikbaar.",
    "step": "Ingestelde stap",
    "attempt": "Berekend gewicht",
    "available": "Toegestane gewichten",
    "nochange": "Geen gedeeltelijke wijziging. Geen afronding of kleinere stap.",
    "W1": "Meerdere passende regels zonder eenduidige voorrang. De trainer moet de bron verduidelijken.",
    "W2": "De volledige gewichtsstap past niet.",
    "missing": "De bron of registratie is onvolledig of niet vergelijkbaar. Geen wijzigingsvoorstel.",
    "replaced": "Vervangen",
    "withdrawn": "Ingetrokken",
    "not_yet_valid": "Nog niet geldig",
    "success": "Servertoestand bijgewerkt.",
    "time": "Tijdstip",
    "action": "Actie",
    "source_append": "Bronversie vastgelegd",
    "source_withdraw": "Bron ingetrokken",
    "consent": "Afzonderlijke lidacceptatie, trainergoedkeuring en toepassing blijven verplicht.",
    "sourceHelp": "RIR en RPE zijn afzonderlijke zelfrapportages. Leeg is niet nul.",
    "new": "Nieuw",
    "noSource": "Geen bron (oorspronkelijk schema)",
    "close": "Sluiten",
    "restored": "Herstelvoorstel van schemaversie",
    "goal": "Doel",
    "optional": "Optioneel",
    "actor": "Actor",
    "binding": "Bronkoppeling"
  },
  "en": {
    "title": "Trainer sources",
    "badge": "6E-10 · Synthetic staging demo",
    "limit": "Fictional plans only. No live AI or real training changes.",
    "login": "Sign in",
    "email": "Test account",
    "password": "Password",
    "logout": "Sign out",
    "refresh": "Refresh",
    "language": "Language",
    "theme": "Theme",
    "light": "Light",
    "dark": "Dark",
    "system": "System",
    "busy": "Working...",
    "retry": "Retry the same request",
    "error": "Not performed. Refresh and check the source and test window.",
    "network": "No response received. The server may have completed the action. Retry the same request.",
    "signin": "Use the existing password for the selected synthetic account.",
    "inactive": "No active test window. No plan or source data is available.",
    "role": "Role",
    "a_member": "Route A · Member",
    "a_trainer": "Route A · Trainer",
    "b_member": "Route B · AI-only member",
    "window": "Test window",
    "ends": "Access until",
    "manage": "Window management",
    "prepare": "Prepare a new window",
    "hours": "Validity in hours",
    "scenario": "Scenario",
    "activate": "Activate window",
    "revoke": "Revoke window",
    "cleanup": "Clean up fixtures",
    "prepared": "Prepared",
    "active": "Active",
    "expired": "Expired",
    "revoked": "Revoked",
    "cleaned": "Cleaned",
    "open": "Open",
    "sources": "Trainer sources",
    "newsource": "New source version",
    "append": "Save source version",
    "withdraw": "Withdraw current source",
    "note": "Trainer note",
    "minSessions": "Required comparable sessions",
    "comparable": "Comparable plan versions",
    "validfrom": "Valid from",
    "validuntil": "Valid until",
    "rules": "Explicit trainer rules",
    "selector": "Binding",
    "exercise": "Exercise",
    "type": "Exercise type",
    "unit": "Unit",
    "minreps": "Min. reps",
    "maxreps": "Max. reps",
    "repstep": "Reps step",
    "resetreps": "Reps after weight step",
    "weightstep": "Weight step",
    "weights": "Allowed weights",
    "minsets": "Min. sets",
    "maxsets": "Max. sets",
    "priority": "Priority (empty = none)",
    "required": "Required",
    "min": "Min.",
    "max": "Max.",
    "addRule": "Add type rule",
    "proposals": "Proposals",
    "propose": "Create new proposal",
    "member_pending": "Awaiting member",
    "member_accepted": "Awaiting trainer",
    "approved": "Approved, awaiting application",
    "applied": "Applied",
    "rejected": "Rejected",
    "blocked": "Blocked",
    "stale": "Outdated source or plan version. Fresh approvals required.",
    "member_accept": "Accept as member",
    "member_reject": "Reject as member",
    "trainer_approve": "Approve as trainer",
    "trainer_reject": "Reject as trainer",
    "trainer_block": "Block as trainer",
    "apply": "Apply change",
    "base": "Current plan target",
    "observed": "Recorded",
    "next": "Proposal",
    "reason": "Reason",
    "reps": "All recorded sets meet the plan target within the trainer limits. The stated reps step fits.",
    "weight": "The stated maximum reps were recorded. The full trainer step fits the allowed weights.",
    "hold": "The records do not meet all stated progression conditions. The target stays unchanged.",
    "history": "Plan history",
    "restore": "Propose restoring",
    "original": "Original source",
    "source": "Source",
    "version": "Version",
    "audit": "Audit history",
    "nothing": "No proposal yet.",
    "emptySource": "No valid trainer source. No change is invented.",
    "b": "Route B has no linked trainer and cannot access trainer sources, A proposals or A plans. 6E-10 introduces no new autonomous platform rules.",
    "step": "Configured step",
    "attempt": "Calculated weight",
    "available": "Allowed weights",
    "nochange": "No partial change. No rounding or smaller step.",
    "W1": "Multiple matching rules without unambiguous priority. The trainer must clarify the source.",
    "W2": "The full weight step does not fit.",
    "missing": "The source or record is incomplete or not comparable. No change proposal.",
    "replaced": "Replaced",
    "withdrawn": "Withdrawn",
    "not_yet_valid": "Not yet valid",
    "success": "Server state updated.",
    "time": "Time",
    "action": "Action",
    "source_append": "Source version saved",
    "source_withdraw": "Source withdrawn",
    "consent": "Separate member acceptance, trainer approval and application remain required.",
    "sourceHelp": "RIR and RPE are separate self-reports. Empty is not zero.",
    "new": "New",
    "noSource": "No source (original plan)",
    "close": "Close",
    "restored": "Restore proposal for plan version",
    "goal": "Goal",
    "optional": "Optional",
    "actor": "Actor",
    "binding": "Source binding"
  },
  "de": {
    "title": "Trainerquellen",
    "badge": "6E-10 · Synthetische Staging-Demo",
    "limit": "Nur fiktive Pläne. Keine Live-KI und keine echten Trainingsänderungen.",
    "login": "Anmelden",
    "email": "Testkonto",
    "password": "Passwort",
    "logout": "Abmelden",
    "refresh": "Aktualisieren",
    "language": "Sprache",
    "theme": "Design",
    "light": "Hell",
    "dark": "Dunkel",
    "system": "System",
    "busy": "Wird verarbeitet...",
    "retry": "Dieselbe Anfrage erneut versuchen",
    "error": "Nicht ausgeführt. Status aktualisieren und Quelle sowie Testfenster prüfen.",
    "network": "Keine Antwort erhalten. Der Server könnte die Aktion bereits ausgeführt haben. Dieselbe Anfrage erneut versuchen.",
    "signin": "Das bestehende Passwort des gewählten synthetischen Kontos verwenden.",
    "inactive": "Kein aktives Testfenster. Keine Plan- oder Quelldaten verfügbar.",
    "role": "Rolle",
    "a_member": "Route A · Mitglied",
    "a_trainer": "Route A · Trainer",
    "b_member": "Route B · KI-only-Mitglied",
    "window": "Testfenster",
    "ends": "Zugang bis",
    "manage": "Fensterverwaltung",
    "prepare": "Neues Fenster vorbereiten",
    "hours": "Gültigkeit in Stunden",
    "scenario": "Szenario",
    "activate": "Fenster aktivieren",
    "revoke": "Fenster widerrufen",
    "cleanup": "Testdaten bereinigen",
    "prepared": "Vorbereitet",
    "active": "Aktiv",
    "expired": "Abgelaufen",
    "revoked": "Widerrufen",
    "cleaned": "Bereinigt",
    "open": "Öffnen",
    "sources": "Trainerquellen",
    "newsource": "Neue Quellenversion",
    "append": "Quellenversion speichern",
    "withdraw": "Aktuelle Quelle zurückziehen",
    "note": "Trainerhinweis",
    "minSessions": "Erforderliche vergleichbare Einheiten",
    "comparable": "Vergleichbare Planversionen",
    "validfrom": "Gültig ab",
    "validuntil": "Gültig bis",
    "rules": "Explizite Trainerregeln",
    "selector": "Zuordnung",
    "exercise": "Übung",
    "type": "Übungstyp",
    "unit": "Einheit",
    "minreps": "Min. Wdh.",
    "maxreps": "Max. Wdh.",
    "repstep": "Wiederholungsschritt",
    "resetreps": "Wdh. nach Gewichtsschritt",
    "weightstep": "Gewichtsschritt",
    "weights": "Erlaubte Gewichte",
    "minsets": "Min. Sätze",
    "maxsets": "Max. Sätze",
    "priority": "Vorrang (leer = keiner)",
    "required": "Erforderlich",
    "min": "Min.",
    "max": "Max.",
    "addRule": "Typregel hinzufügen",
    "proposals": "Vorschläge",
    "propose": "Neuen Vorschlag erstellen",
    "member_pending": "Wartet auf Mitglied",
    "member_accepted": "Wartet auf Trainer",
    "approved": "Genehmigt, noch anzuwenden",
    "applied": "Angewendet",
    "rejected": "Abgelehnt",
    "blocked": "Blockiert",
    "stale": "Veraltete Quellen- oder Planversion. Neue Zustimmungen erforderlich.",
    "member_accept": "Als Mitglied akzeptieren",
    "member_reject": "Als Mitglied ablehnen",
    "trainer_approve": "Als Trainer genehmigen",
    "trainer_reject": "Als Trainer ablehnen",
    "trainer_block": "Als Trainer blockieren",
    "apply": "Änderung anwenden",
    "base": "Aktuelles Planziel",
    "observed": "Erfasst",
    "next": "Vorschlag",
    "reason": "Begründung",
    "reps": "Alle erfassten Sätze erreichen das Planziel innerhalb der Trainergrenzen. Der festgelegte Wiederholungsschritt passt.",
    "weight": "Die festgelegte maximale Wiederholungszahl wurde erfasst. Der volle Trainerschritt passt zu den erlaubten Gewichten.",
    "hold": "Die Aufzeichnungen erfüllen nicht alle festgelegten Fortschrittsbedingungen. Das Ziel bleibt gleich.",
    "history": "Planverlauf",
    "restore": "Wiederherstellung vorschlagen",
    "original": "Ursprüngliche Quelle",
    "source": "Quelle",
    "version": "Version",
    "audit": "Auditverlauf",
    "nothing": "Noch kein Vorschlag.",
    "emptySource": "Keine gültige Trainerquelle. Keine Änderung wird erfunden.",
    "b": "Route B hat keinen verknüpften Trainer und keinen Zugriff auf Trainerquellen, A-Vorschläge oder A-Pläne. 6E-10 enthält keine neuen autonomen Plattformregeln.",
    "step": "Festgelegter Schritt",
    "attempt": "Berechnetes Gewicht",
    "available": "Erlaubte Gewichte",
    "nochange": "Keine teilweise Änderung. Keine Rundung und kein kleinerer Schritt.",
    "W1": "Mehrere passende Regeln ohne eindeutigen Vorrang. Der Trainer muss die Quelle klären.",
    "W2": "Der vollständige Gewichtsschritt passt nicht.",
    "missing": "Quelle oder Aufzeichnung unvollständig oder nicht vergleichbar. Kein Änderungsvorschlag.",
    "replaced": "Ersetzt",
    "withdrawn": "Zurückgezogen",
    "not_yet_valid": "Noch nicht gültig",
    "success": "Serverstatus aktualisiert.",
    "time": "Zeitpunkt",
    "action": "Aktion",
    "source_append": "Quellenversion gespeichert",
    "source_withdraw": "Quelle zurückgezogen",
    "consent": "Mitgliedszustimmung, Trainergenehmigung und Anwendung bleiben getrennt erforderlich.",
    "sourceHelp": "RIR und RPE sind getrennte Selbstauskünfte. Leer ist nicht null.",
    "new": "Neu",
    "noSource": "Keine Quelle (ursprünglicher Plan)",
    "close": "Schließen",
    "restored": "Wiederherstellungsvorschlag für Planversion",
    "goal": "Ziel",
    "optional": "Optional",
    "actor": "Akteur",
    "binding": "Quellenbindung"
  }
};
