"use strict";
const fs=require('node:fs'),p=require('node:path'),a=require('node:assert/strict'),{chromium}=require('C:/Users/Fitme/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {server,allowed}=require('./serve.cjs'),R=require('../../combined-plan-demo/review.js'),out=process.argv[2],remote=process.argv.includes('--published');
const result={remote,checks:[],layouts:[],errors:[],requests:[],screenshots:[]},check=(name,pass)=>{result.checks.push({name,pass:!!pass});a(pass,name);},stamp=Date.now();
(async()=>{let serverInstance,browser;try{
 let base='https://yourizorge.github.io/fitmetzorge-staging';if(!remote){serverInstance=server();await new Promise(r=>serverInstance.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+serverInstance.address().port;}
 browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 async function open(width,height=900){const ctx=await browser.newContext({viewport:{width,height},serviceWorkers:'block'});
  await ctx.addInitScript(()=>{window.__writes=[];for(const k of ['localStorage','sessionStorage','indexedDB'])Object.defineProperty(window,k,{get(){window.__writes.push(k);throw Error('storage_blocked');}});Object.defineProperty(document,'cookie',{get(){return '';},set(){window.__writes.push('cookie');}});});
  await ctx.route('**/*',r=>{const q=r.request(),u=new URL(q.url()),prefix=remote?'/fitmetzorge-staging':'',ok=q.method()==='GET'&&u.origin===new URL(base).origin&&allowed.includes(u.pathname.slice(prefix.length));result.requests.push({path:u.pathname,allowed:ok});if(!ok){result.errors.push('egress');return r.abort();}return r.continue();});
  const page=await ctx.newPage();page.on('pageerror',e=>result.errors.push(e.message));await page.goto(base+'/combined-plan-demo/index.html',{waitUntil:'networkidle'});return {page,ctx};
 }
 async function layout(page,key){const bad=await page.evaluate(()=>[...document.querySelectorAll('main *,header *')].filter(e=>{const r=e.getBoundingClientRect();return e.tagName!=='OPTION'&&r.width&&r.height&&(r.left<-.5||r.right>innerWidth+.5);}).map(e=>e.tagName+'.'+e.className));result.layouts.push({key,overflow:bad});check(key+' no overflow',bad.length===0);check(key+' unique IDs',await page.locator('[id]').evaluateAll(es=>new Set(es.map(e=>e.id)).size===es.length));}
 for(const width of [320,390,768,1280])for(const language of ['nl','en','de'])for(const theme of ['light','dark']){
  const {page,ctx}=await open(width),key=width+'-'+language+'-'+theme;await page.selectOption('#language',language);await page.selectOption('#theme',theme);
  check(key+' sixteen scenarios',await page.locator('#scenario-buttons button').count()===16);check(key+' brand',await page.locator('header img').evaluate(e=>e.naturalWidth>0));check(key+' touch targets',await page.locator('#scenario-buttons button').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().height>=64)));
  for(const c of R.scenarios){await page.click('#test-'+c.id);check(key+' '+c.id+' PASS',await page.locator('#verdict').getAttribute('data-result')==='pass');check(key+' '+c.id+' title',await page.locator('#scenario-title').innerText()===c.title[['nl','en','de'].indexOf(language)]);check(key+' '+c.id+' result visible',await page.locator('#verdict').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}));await layout(page,key+' '+c.id);}
  await page.click('#test-valid');check(key+' exact energy',await page.locator('#proposal-energy').innerText()==='1725');check(key+' no automatic version',await page.locator('#versions').getAttribute('data-count')==='0');
  await page.click('#test-allergy');check(key+' no unsafe plan',await page.locator('#proposal-energy').count()===0&&await page.locator('#confirm,#activate').count()===0);
  await page.click('#test-consent');check(key+' disabled after revocation',await page.locator('#build').isDisabled()&&await page.locator('#source-change').isDisabled());
  await page.click('#test-units');check(key+' distinct units',await page.locator('#plans').innerText().then(s=>s.includes('20 kg')&&s.includes('165 lb')&&s.includes('RIR 0')));
  if(language==='nl'&&(width===390||width===1280)){await page.click('#test-valid');await page.locator('#review').scrollIntoViewIfNeeded();let file=p.join(out,(remote?'published':'local')+'-'+stamp+'-'+key+'.png');await page.screenshot({path:file});result.screenshots.push(file);await page.locator('#plans').scrollIntoViewIfNeeded();file=p.join(out,(remote?'published':'local')+'-'+stamp+'-plan-'+key+'.png');await page.screenshot({path:file});result.screenshots.push(file);}
  check(key+' no storage',(await page.evaluate(()=>window.__writes)).length===0);await ctx.close();
 }
 const {page,ctx}=await open(390,480);await page.locator('#start').focus();await page.keyboard.press('Enter');check('guided first',await page.locator('#previous').isDisabled());
 for(let i=1;i<16;i++){await page.click('#next');check('guided '+i,await page.locator('#step').innerText()==='Stap '+(i+1)+' van 16'&&await page.locator('#verdict').getAttribute('data-result')==='pass');}check('guided last',await page.locator('#next').isDisabled());await page.click('#previous');check('guided previous',await page.locator('#step').innerText()==='Stap 15 van 16');
 await page.click('#test-valid');await page.evaluate(()=>{$('proposal-energy').textContent='999';renderReview();});check('corrupted nutrition red',await page.locator('#verdict').getAttribute('data-result')==='fail');
 await page.click('#test-valid');await page.evaluate(()=>{document.querySelector('.exercise p').textContent='wrong';renderReview();});check('corrupted training red',await page.locator('#verdict').getAttribute('data-result')==='fail');
 await page.click('#test-valid');await page.evaluate(()=>{review.events.pop();renderReview();});check('missing proof red',await page.locator('#verdict').getAttribute('data-result')==='fail');
 await page.click('#test-valid');await page.click('#confirm');check('separate activation',await page.locator('#activate').count()===1&&await page.locator('#versions').getAttribute('data-count')==='0');await page.click('#activate');await page.click('#duplicate');check('one version',await page.locator('#versions').getAttribute('data-count')==='1');
 await page.click('#build');await page.click('#confirm');await page.selectOption('#edit-training_day','fri');check('manual clears verdict',await page.locator('#verdict').getAttribute('data-result')===null);await page.click('#save-training_day');check('edit invalidates approval',await page.locator('#confirm').count()===1&&await page.locator('#activate').count()===0);
 await page.selectOption('#edit-nutrition_moment','20:00');await page.click('#save-nutrition_moment');await page.click('#confirm');await page.click('#activate');
 check('changed both domains',await page.locator('#versions').innerText().then(s=>s.includes('fri')&&s.includes('20:00')));await page.click('#restore');check('restore pending',await page.locator('#confirm').count()===1&&await page.locator('#versions').getAttribute('data-count')==='2');await page.click('#confirm');await page.click('#activate');check('restore three immutable versions',await page.locator('#versions').getAttribute('data-count')==='3'&&await page.locator('.version').last().innerText().then(s=>s.includes('mon')&&s.includes('08:00')));
 await page.click('#source-change');check('source invalidates',await page.locator('#proposal-energy').count()===0&&await page.locator('#confirm,#activate').count()===0);await page.click('#build');await page.click('#reject');check('reject no apply',await page.locator('#confirm,#activate').count()===0&&await page.locator('#versions').getAttribute('data-count')==='3');
 await page.click('#revoke');check('withdraw disabled',await page.locator('#build').isDisabled());await layout(page,'keyboard-space');
 await page.reload({waitUntil:'networkidle'});check('refresh reset',await page.locator('#audit li').count()===0&&await page.locator('#verdict').getAttribute('data-result')===null);await ctx.close();check('no errors or extra egress',result.errors.length===0);result.status='BROWSER_PASS';
 }catch(e){result.status='BROWSER_FAIL';result.failure=e.message;process.exitCode=1;}finally{if(browser)await browser.close();if(serverInstance)await new Promise(r=>serverInstance.close(r));fs.writeFileSync(p.join(out,(remote?'published':'local')+'-browser-'+Date.now()+'.json'),JSON.stringify(result,null,2),{flag:'wx'});console.log(JSON.stringify({status:result.status,checks:result.checks.length,layouts:result.layouts.length,errors:result.errors,failure:result.failure}));}
})();
