"use strict";
const fs=require('node:fs'),p=require('node:path'),crypto=require('node:crypto'),a=require('node:assert/strict'),R=require('../../combined-plan-demo/review.js'),L=require('../../combined-plan-demo/copy.js');
const root=p.resolve(__dirname,'../..'),out=process.argv[2],sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),read=f=>JSON.parse(fs.readFileSync(f)),latest=(prefix,dir=out)=>p.join(dir,fs.readdirSync(dir).filter(f=>f.startsWith(prefix)&&f.endsWith('.json')).sort().at(-1));
const files=[latest('contract-'),latest('contract-',p.join(out,'frozen17')),latest('contract-',p.join(out,'frozen16')),p.join(out,'unit-regressions.json'),latest('6e13-tests-'),latest('6e14-tests-')];
const groups=files.flatMap(f=>{const x=read(f);return x.groups?Object.entries(x.groups).map(([name,g])=>({name,counts:g.counts,exit:g.exit})):[{name:p.relative(out,f),counts:x.counts,exit:x.status??x.exit}];});
for(const g of groups){a.equal(g.exit,0,g.name);a.equal(g.counts.fail,0);a.equal(g.counts.skipped,0);a.equal(g.counts.pass,g.counts.tests);}const total=groups.reduce((n,g)=>n+g.counts.tests,0);a.equal(total,4373);
const browserFile=latest('local-browser-'),b=read(browserFile),preserveFile=latest('preserve-'),preserve=read(preserveFile);a.equal(b.status,'BROWSER_PASS');a.equal(b.checks.length,2171);a(b.checks.every(x=>x.pass));a.equal(b.layouts.length,385);a.equal(preserve.status,'PASS');
const sources=[];for(const dir of ['combined-plan-demo','_offline/phase6e18'])for(const f of fs.readdirSync(p.join(root,dir)))if(fs.statSync(p.join(root,dir,f)).isFile())sources.push(dir+'/'+f);
const evidence={package:'6E-18',status:'LOCAL TECHNICAL PASS; publication separately verified',baseline:read(p.join(out,'before.json')).head,source_sha256:Object.fromEntries(sources.map(f=>[f,sha(p.join(root,f))])),tests:{total,new18:335,frozen:4038,groups,known_limitations_not_recognition_success:true,nutrition_medical_validation:false},browser:{checks:b.checks.length,layouts:b.layouts.length,settings:24,emulated_only:true},preservation:preserve,raw_sha256:Object.fromEntries([...files,browserFile,preserveFile].map(f=>[p.relative(root,f).replaceAll('\\','/'),sha(f)])),owner_accepted:false,frozen:false,hosted_supabase_calls:0,external_ai_calls:0,real_member_ai:false,support_hold:'SU-487979'};
const examples=[];
for(const spec of R.scenarios){const r=R.run(spec.id),s=r.model.view();a(R.assess(r,s).pass);examples.push({scenario:spec.id,sourceRevision:s.sources.revision,status:s.status,version:s.version,bundle:s.draft??s.active??null,answers:['nl','en','de'].map((language,i)=>({language,title:spec.title[i],changed:spec.changed[i],message:L.reason(r.events.at(-1).reason,i)})),events:r.events,pass:true});}
for(const [file,data]of [['PHASE6E18_EVIDENCE.json',evidence],['PHASE6E18_EXAMPLES.json',examples]])fs.writeFileSync(p.join(root,'docs',file),JSON.stringify(data,null,2)+'\n',{flag:'wx'});console.log({total,sources:sources.length,scenarios:examples.length,answers:examples.length*3});
