'use strict';
const fs=require('node:fs'),p=require('node:path'),c=require('node:crypto'),a=require('node:assert/strict'),R=require('../../daily-coach-demo/review.js'),C=require('../../daily-coach-demo/copy.js');
const root=p.resolve(__dirname,'../..'),out=process.argv[2],sha=x=>c.createHash('sha256').update(x).digest('hex'),read=f=>JSON.parse(fs.readFileSync(p.join(out,f))),names=fs.readdirSync(out),last=prefix=>names.filter(f=>f.startsWith(prefix)&&f.endsWith('.json')).sort().at(-1);
const unit=read(last('contract-'));a.equal(unit.counts.tests,231);a.equal(unit.counts.pass,231);a.equal(unit.counts.fail,0);
const browser=read(last('local-browser-'));a.equal(browser.status,'BROWSER_PASS');a.equal(browser.layouts.length,433);a(browser.checks.every(x=>x.pass));for(const [f,h]of Object.entries(browser.source_sha256))a.equal(sha(fs.readFileSync(p.join(root,'daily-coach-demo',f))),h,f);
let frozen=0;for(const x of Object.values(read('unit-regressions.json').groups)){a.equal(x.exit,0);a.equal(x.counts.fail,0);frozen+=x.counts.pass;}
for(const [n,count]of [[13,233],[14,389],[16,536],[17,289],[18,335],[19,343]]){const r=read(last('suite-result-'+n+'-'));a.equal(r.exit,0);a.equal(r.counts.pass,count);frozen+=count;}a.equal(frozen,4716);
const preserve=read(last('preserve-'));a.equal(preserve.status,'PASS');a.equal(preserve.files,1290);a.equal(preserve.historical,58);
const pub=read(last('publication-before-'));a.equal(pub.status,'PUBLICATION_PASS');a.equal(pub.existing.length,140);
const files=[];for(const d of ['_offline/phase6e20','daily-coach-demo'])for(const f of fs.readdirSync(p.join(root,d)).filter(f=>fs.statSync(p.join(root,d,f)).isFile()))files.push(d+'/'+f);
const evidence={package:'6E-20',status:'LOCAL_TECHNICAL_PASS; publication separately verified',source_sha256:Object.fromEntries(files.map(f=>[f,sha(fs.readFileSync(p.join(root,f)))])),tests:{new20:unit.counts,frozen,total:frozen+unit.counts.pass,network_blocked:true,medical_validation:false,known_limitation_observations_not_recognition_success:true},browser:{assertions:browser.checks.length,layouts:browser.layouts.length,settings:24,scenarios:18,widths:[320,390,768,1280],languages:['nl','en','de'],themes:['light','dark'],physical_phone:false,no_unexpected_requests:browser.errors.length===0},preserve,publication_before:{old:140,private404:pub.private.length},raw_evidence:Object.fromEntries(names.filter(f=>f.endsWith('.json')).map(f=>[p.relative(root,p.join(out,f)).replaceAll('\\','/'),sha(fs.readFileSync(p.join(out,f)))])),screenshots:browser.screenshots.map(f=>({file:p.relative(root,f).replaceAll('\\','/'),sha256:sha(fs.readFileSync(f))})),support_hold:'SU-487979',external_ai_calls:0,external_cost_eur:0,real_member_ai:false,production_touched:false,owner_accepted:false};
const examples=[];for(const spec of R.scenarios)for(let l=0;l<3;l++){const r=R.run(spec.id),s=r.model.view();a(R.assess(r).pass);examples.push({case:spec.id,language:['nl','en','de'][l],title:spec.title[l],status:C.get(s.status,l),message:C.reason(r.last&&!r.last.ok?r.last.reason:s.reason,l),expected:C.reason(spec.reason,l),sourceRevision:s.sourceRevision,appliedVersion:s.active.version,facts:s.facts,proposal:s.proposal?{kind:s.proposal.kind,rule:s.proposal.rule,cadence:s.proposal.target.cadence,trainingDay:s.route==='B'?s.proposal.target.training.sessions[0].day:null,firstMeal:s.proposal.target.nutrition.meals[0].moment}:null,registered:s.records.map(x=>({id:x.id,version:x.revision,plan:x.planVersion,planned:x.planned,actual:x.value,rir:x.actualRir,rpe:x.actualRpe})),automatic_actions_allowed:false});}
for(const [file,data]of [['docs/PHASE6E20_EVIDENCE.json',evidence],['docs/PHASE6E20_EXAMPLES.json',examples]])fs.writeFileSync(p.join(root,file),JSON.stringify(data,null,2)+'\n',{flag:'wx'});
console.log({status:evidence.status,sources:files.length,total:evidence.tests.total,browser:evidence.browser.assertions,examples:examples.length});
