"use strict";
const t=require("node:test"),a=require("node:assert/strict"),fs=require("node:fs"),crypto=require("node:crypto");
const M=require("../../training-rules-demo/model.js"),C=require("../../training-rules-demo/catalog.js"),F=require("../../training-rules-demo/fixtures.js"),R=require("../../training-rules-demo/review.js"),L=require("../../training-rules-demo/copy.js"),clone=x=>JSON.parse(JSON.stringify(x));
const create=(name="beginner")=>M.create(F.cases[name]),cmd=(m,action,data={})=>m.command(m.event(action,data)),built=(n="beginner")=>{const m=create(n);a(cmd(m,"build").ok);return m;},activate=m=>{a(cmd(m,"confirm").ok);a(cmd(m,"activate").ok);};
for(const c of R.scenarios)for(const lang of [0,1,2]){
 t(c.id+" owner run "+lang,()=>{const r=R.run(c.id);a(R.assess(r,r.model.view(),R.visibleFacts(r.model.view())).pass,JSON.stringify(r.checks));a(c.title[lang]);a(c.expected[lang]);a.equal(r.model.view().external_calls,0);});
 t(c.id+" missing proof cannot PASS "+lang,()=>{const r=R.run(c.id);r.events.pop();a.equal(R.assess(r,r.model.view()).pass,false);});
}
for(const goal of M.goals)for(const experience of M.experiences)for(const frequency of [2,4]){
 t("rule match "+[goal,experience,frequency].join("/"),()=>{const f=clone(F.base);Object.assign(f.intake,{goal,experience,frequency,days:["mon","tue","thu","sat"]});const m=M.create(f),r=cmd(m,"build");a(r.ok);a.equal(r.state.draft.plan.sessions.length,frequency);const rows=r.state.draft.plan.sessions[0].exercises;a.notEqual(rows[0].sets,rows[1].sets);a.notEqual(rows[0].rule,rows[1].rule);for(const s of r.state.draft.plan.sessions)a(s.seconds<=r.state.draft.plan.budget);});
}
for(const field of M.fields)t("missing intake "+field,()=>{const f=clone(F.base);delete f.intake[field];const m=M.create(f),before=m.view();a.equal(cmd(m,"build").ok,false);a.deepEqual(m.view(),before);});
for(const key of ["sets","reps","rest","rir","rpe"])for(const invalid of [-1,null,1.5,999]){
 t(key+" invalid "+invalid,()=>{const m=built("both"),before=m.view();a.equal(cmd(m,"edit",R.exerciseEdit(m,{[key]:invalid})).ok,false);a.deepEqual(m.view(),before);});
}
for(const rir of [true,false])for(const rpe of [true,false])t("independent effort "+rir+"/"+rpe,()=>{const f=clone(F.base);Object.assign(f.intake,{rir,rpe});const m=M.create(f);a(cmd(m,"build").ok);for(const e of m.view().draft.plan.sessions[0].exercises){a.equal(e.rir===null,!rir);a.equal(e.rpe===null,!rpe);}});
t("RIR zero remains0, missing is null",()=>{const m=built("both");a(cmd(m,"edit",R.exerciseEdit(m,{rir:0})).ok);a.equal(m.view().draft.plan.sessions[0].exercises[0].rir,0);a.equal(cmd(m,"edit",R.exerciseEdit(m,{rir:null})).ok,false);});
t("bounded edits include alternative/day/rest and confirmation invalidation",()=>{const m=built();a(cmd(m,"confirm").ok);a(cmd(m,"edit",R.exerciseEdit(m,{exercise:"press",sets:3,reps:11,rest:75})).ok);a.equal(m.view().confirmed,false);a.equal(cmd(m,"activate").ok,false);a(cmd(m,"edit",{kind:"day",session:0,day:"fri"}).ok);activate(m);a.equal(m.view().version,1);});
t("duplicate day and unavailable day refused atomically",()=>{for(const day of ["wed","sun"]){const m=built(),before=m.view();a.equal(cmd(m,"edit",{kind:"day",session:0,day}).ok,false);a.deepEqual(m.view(),before);}});
t("exact arithmetic no hidden time",()=>{const m=built(),s=m.view(),p=s.draft.plan;for(const session of p.sessions){let total=s.catalog.overhead_seconds;for(const x of session.exercises){const r=M.selectRule(s.catalog,s.intake,x.role);a.equal(x.seconds,45+x.sets*x.reps*3+(x.sets-1)*x.rest);total+=x.seconds;}a.equal(session.seconds,total);}});
t("within ranges but outside time budget is refused",()=>{const m=built("short"),before=m.view();a.equal(cmd(m,"edit",R.exerciseEdit(m,{sets:3,reps:12,rest:120})).reason,"time_budget");a.deepEqual(m.view(),before);});
for(const key of ["sets","reps","rest","rir","rpe"])t("malformed range "+key,()=>{const f=clone(F.base);f.catalog.rules[0][key].step=0;const m=M.create(f);a.equal(cmd(m,"build").reason,"rule");});
for(const kind of ["missing","conflict","expired","future","unknown_exercise","bad_progression","bad_layout"])t("catalog refusal "+kind,()=>{
 const f=clone(F.base);if(kind==="missing")f.catalog.rules=[];if(kind==="conflict"){const r=clone(f.catalog.rules[0]);r.id+="-duplicate";f.catalog.rules.push(r);}if(kind==="expired")f.catalog.expires=f.clock;if(kind==="future")f.catalog.effective=f.clock+1;if(kind==="unknown_exercise")f.catalog.exercises[0].id="other";if(kind==="bad_progression")f.catalog.rules[0].progression.automatic=true;if(kind==="bad_layout")f.catalog.layouts[0].roles=["main"];
 const m=M.create(f),before=m.view();a.equal(cmd(m,"build").ok,false);a.deepEqual(m.view(),before);
});
for(const change of ["person","exercise","session","expired","future","unit","negative","duplicate","tie","rir","rpe","missing"])t("invalid history "+change,()=>{
 const f=clone(F.cases.units),h=f.intake.history[0];
 if(["person","exercise","session"].includes(change))h[change]="wrong";if(change==="expired")h.expires=f.clock;if(change==="future")h.at=f.clock+1;if(change==="unit")h.weight.unit="stone";if(change==="negative")h.weight.value=-1;if(change==="duplicate")f.intake.history.push(clone(h));if(change==="tie"){const x=clone(h);x.id+="-2";f.intake.history.push(x);}if(change==="rir")h.rir=-1;if(change==="rpe")h.rpe=0;if(change==="missing")delete h.weight;
 const m=M.create(f);a.equal(cmd(m,"build").ok,false);
});
for(const value of [null,0,20])for(const unit of ["kg","lb"])t("history source retained "+value+unit,()=>{
 const f=clone(F.cases.units);f.intake.history[0].weight={value,unit};const m=M.create(f);a(cmd(m,"build").ok);activate(m);const old=clone(m.view().history),i=m.view().intake;i.unit=unit==="kg"?"lb":"kg";a(cmd(m,"intake",i).ok);a(cmd(m,"build").ok);a.deepEqual(m.view().draft.plan.sessions[0].exercises[0].history.weight,{value,unit});a.equal(m.view().draft.plan.sessions[0].exercises[0].load,null);a.deepEqual(m.view().history,old);
});
t("latest exact record selected, no cross-exercise matching",()=>{const f=clone(F.cases.units),h=clone(f.intake.history[0]);h.id+="-new";h.at+=1000;h.weight.value=22;f.intake.history.push(h);const m=M.create(f);a(cmd(m,"build").ok);const es=m.view().draft.plan.sessions[0].exercises;a.equal(es[0].history.weight.value,22);a.equal(es[1].history,null);});
for(const key of ["goal","experience","days","equipment"])t("changed "+key+" clears draft but preserves history",()=>{const m=built();activate(m);const old=m.view().history,i=m.view().intake;i[key]={goal:"strength",experience:"experienced",days:["tue","thu"],equipment:["mat"]}[key];a(cmd(m,"intake",i).ok);a.equal(m.view().draft,null);a.equal(m.view().confirmed,false);a.equal(cmd(m,"activate").ok,false);a.deepEqual(m.view().history,old);a(cmd(m,"build").ok);});
for(const health of M.health.filter(x=>x!=="none"))t("frozen safety "+health,()=>{const f=clone(F.base);f.intake.health=health;const m=M.create(f);a.equal(cmd(m,"build").reason,"safety");const i=m.view().intake;i.health="none";a(cmd(m,"intake",i).ok);a.equal(cmd(m,"build").reason,"safety");});
t("consent blocks build/intake/source/activation after revoke",()=>{const m=built();a(cmd(m,"revoke").ok);const old=m.view();for(const [action,data]of [["build",{}],["intake",F.base.intake],["source",C.data],["activate",{}]]){a.equal(cmd(m,action,data).ok,false);a.deepEqual(m.view(),old);}});
t("source correction invalidates stale event",()=>{const m=built();a(cmd(m,"confirm").ok);const e=m.event("activate"),c=m.view().catalog;c.version++;a(cmd(m,"source",c).ok);a.equal(m.command(e).reason,"version_conflict");a.equal(m.view().draft,null);a(cmd(m,"build").ok);a.equal(m.view().draft.plan.catalogVersion,2);});
t("changed source refuses restoration of old source",()=>{const m=built();activate(m);a(cmd(m,"build").ok);activate(m);const c=m.view().catalog;c.version++;a(cmd(m,"source",c).ok);a.equal(cmd(m,"restore",{version:1}).reason,"plan_source");a.equal(m.view().history.length,2);});
for(const field of ["id","route","person","binding"])t("request mismatch "+field,()=>{const m=built(),before=m.view(),e=m.event("confirm");e[field]="other";a.equal(m.command(e).ok,false);a.deepEqual(m.view(),before);});
t("same request with changed payload refuses",()=>{const m=built(),e=m.event("confirm");a(m.command(e).ok);e.data.extra=true;const before=m.view();a.equal(m.command(e).reason,"duplicate_conflict");a.deepEqual(m.view(),before);});
t("activation failure is atomic and retry exact explicit request succeeds once",()=>{const m=built();a(cmd(m,"confirm").ok);const before=m.view(),e=m.event("activate");a.equal(m.command(e,{fault_before_commit:true}).reason,"atomic_fault");a.deepEqual(m.view(),before);a(m.command(e).ok);a.equal(m.command(e).reason,"idempotent");a.equal(m.view().version,1);});
t("rejection cannot activate",()=>{const m=built();a(cmd(m,"reject").ok);a.equal(cmd(m,"activate").ok,false);a.equal(m.view().version,0);});
t("display corruption cannot PASS",()=>{const r=R.run("beginner"),d=R.visibleFacts(r.model.view());d.rows[0].sets="99";a.equal(R.assess(r,r.model.view(),d).pass,false);r.checks=[];a.equal(R.assess(r,r.model.view()).pass,false);});
t("wrong executor cannot greenlight",()=>{const r=R.run("beginner",f=>{const m=M.create(f);return {...m,command:()=>({ok:false,reason:"injected"})};});a.equal(R.assess(r,r.model.view()).pass,false);});
t("copy complete for three locales",()=>{for(const group of [L.w,L.labels,L.values,L.errors])for(const value of Object.values(group))a(value.length===3&&value.every(x=>typeof x==="string"&&x.length));});
t("frozen15 exact source hashes",()=>{const f=JSON.parse(fs.readFileSync("docs/PHASE6E15_FREEZE_EVIDENCE.json"));a.equal(f.sources.length,21);for(const x of f.sources)a.equal(crypto.createHash("sha256").update(fs.readFileSync(x.file)).digest("hex"),x.working_sha256,x.file);});
t("static isolated demo has no provider/storage/private dependencies",()=>{for(const f of fs.readdirSync("training-rules-demo")){const s=fs.readFileSync("training-rules-demo/"+f,"utf8");a.doesNotMatch(s,/\b(fetch|XMLHttpRequest|WebSocket|localStorage|sessionStorage|indexedDB)\b|_offline\/|supabase\.co|service_role|sb_secret_/);}});
