(function(root){"use strict";
const w={
 title:["Youri | Trainingsregels","Youri | Training rules","Youri | Trainingsregeln"],
 demo:["Synthetische offline demo. Conceptregels, niet deskundig beoordeeld. Alleen geheugen; verversen reset alles.","Synthetic offline demo. Concept rules, not expert reviewed. Memory only; refresh resets all.","Synthetische Offline-Demo. Konzeptregeln, nicht fachlich geprueft. Nur im Speicher; Neuladen setzt alles zurueck."],
 tests:["Testscenario's","Test scenarios","Testszenarien"],start:["Start begeleide owner-test","Start guided owner test","Begleitete Tests starten"],previous:["Vorige stap","Previous step","Vorheriger Schritt"],next:["Volgende stap","Next step","Naechster Schritt"],
 steps:["Stap","Step","Schritt"],of:["van","of","von"],choose:["Kies een test","Choose a test","Test waehlen"],expected:["Verwachte uitkomst","Expected outcome","Erwartetes Ergebnis"],
 pass:["PASS - zichtbaar resultaat klopt","PASS - visible result matches","PASS - sichtbares Ergebnis stimmt"],fail:["AFWIJKING - nog niet goedkeuren","MISMATCH - do not approve yet","ABWEICHUNG - noch nicht freigeben"],
 testNote:["Iedere test gebruikt verse fictieve gegevens. Bevestigen en activeren worden waar nodig alleen gesimuleerd. PASS is geen medische goedkeuring of owneracceptatie.","Each test uses fresh fictional data. Confirmation/activation are simulated when needed. PASS is not medical or owner approval.","Jeder Test nutzt neue fiktive Daten. Bestaetigung/Aktivierung werden gegebenenfalls simuliert. PASS ist keine medizinische oder Owner-Freigabe."],
 intake:["Intake en bron","Intake and source","Angaben und Quelle"],save:["Intake bewaren en opnieuw beoordelen","Save intake for reassessment","Angaben zur Neubewertung speichern"],build:["Voorstel maken","Build proposal","Vorschlag erstellen"],confirm:["Voorstel bevestigen","Confirm proposal","Vorschlag bestaetigen"],activate:["Afzonderlijk activeren","Activate separately","Getrennt aktivieren"],reject:["Afwijzen","Reject","Ablehnen"],restore:["Vorige versie voorstellen","Propose previous version","Vorherige Version vorschlagen"],duplicate:["Dubbele activering testen","Test duplicate activation","Doppelte Aktivierung testen"],
 source:["Bronversie corrigeren","Correct source version","Quellversion korrigieren"],revoke:["Toestemming intrekken","Withdraw consent","Einwilligung widerrufen"],reset:["Opnieuw beginnen","Reset demo","Neu beginnen"],review:["Nieuwe beoordeling nodig","Reassessment required","Neubewertung erforderlich"],
 draft:["Voorgestelde waarden","Proposed values","Vorgeschlagene Werte"],before:["Waarden voor deze testbewerking","Values before this test edit","Werte vor dieser Testaenderung"],empty:["Geen voorstel","No proposal","Kein Vorschlag"],noBefore:["Geen eerder concept in deze test.","No earlier draft in this test.","Kein vorheriger Entwurf in diesem Test."],
 rule:["Regel","Rule","Regel"],catalog:["Catalogus","Catalog","Katalog"],reason:["Reden","Reason","Grund"],option:["Gekozen optie","Selected option","Gewaehlt"],alternatives:["Beschikbare alternatieven","Available alternatives","Verfuegbare Alternativen"],edit:["Bewerking beoordelen","Review edit","Aenderung pruefen"],
 sets:["Sets","Sets","Saetze"],reps:["Herhalingen","Reps","Wiederholungen"],rest:["Rust (sec)","Rest (sec)","Pause (Sek)"],day:["Trainingsdag","Training day","Trainingstag"],role:["Rol","Role","Rolle"],
 budget:["Tijdsbudget","Time budget","Zeitbudget"],estimate:["Conceptplanning, geen meting van belastbaarheid","Concept planning, not a capacity measurement","Konzeptplanung, keine Belastbarkeitsmessung"],
 formula:["Opstart + uitvoering + pauzes + wisseltijd","Setup + execution + rest + transitions","Vorbereitung + Ausfuehrung + Pausen + Wechsel"],
 progression:["Toegestane reps-stap; niet automatisch uitgevoerd","Allowed rep step; not automatically executed","Erlaubter Wiederholungsschritt; nicht automatisch ausgefuehrt"],
 load:["Nieuw startgewicht: ontbreekt","New initial load: missing","Neues Startgewicht: fehlt"],history:["Historische bron","Historical source","Historische Quelle"],missingHistory:["Geen gekoppelde gewichtsregistratie","No linked weight record","Keine verknuepfte Gewichtsaufzeichnung"],
 unitsNote:["Bronwaarde en broneenheid blijven exact gelijk. Er vindt geen conversie of nieuw gewichtsadvies plaats.","Source value and unit stay unchanged. No conversion or new load advice.","Quellwert und Einheit bleiben unveraendert. Keine Umrechnung oder neue Gewichtsempfehlung."],
 selfReport:["RIR/RPE zijn afzonderlijke zelfrapportages.","RIR/RPE are separate self-reports.","RIR/RPE sind getrennte Selbstauskuenfte."],
 versions:["Planversies","Plan versions","Planversionen"],audit:["Testhistorie","Test history","Testverlauf"],oldActive:["Eerdere actieve versie blijft behouden","Earlier active version retained","Fruehere aktive Version bleibt erhalten"],
 unchanged:["Geweigerd; het vorige concept is ongewijzigd. Hieronder staan de beschikbare bereiken.","Refused; previous draft unchanged. Available ranges are shown below.","Abgelehnt; vorheriger Entwurf unveraendert. Verfuegbare Bereiche stehen unten."],
 blocked:["Geblokkeerd concept; niet bevestigen of activeren.","Blocked draft; cannot confirm or activate.","Gesperrter Entwurf; keine Bestaetigung oder Aktivierung."],
 details:["Uitgevoerde controles","Executed checks","Ausgefuehrte Pruefungen"],manual:["Handmatige wijziging: kies opnieuw een test voor een actuele PASS.","Manual change: rerun a test for a current PASS.","Manuelle Aenderung: Test fuer aktuelles PASS erneut starten."],
 scope:["Route B, uitsluitend fictief. Geen echte planwijziging, geen live AI. 6E-11: SUPPORT HOLD SU-487979.","Route B, fictional only. No real plan change or live AI. 6E-11: SUPPORT HOLD SU-487979.","Route B, nur fiktiv. Keine echte Planaenderung oder Live-KI. 6E-11: SUPPORT HOLD SU-487979."]
};
const labels={goal:["Doel","Goal","Ziel"],experience:["Ervaring","Experience","Erfahrung"],frequency:["Trainingen per week","Sessions per week","Einheiten pro Woche"],minutes:["Minuten per sessie","Minutes per session","Minuten pro Einheit"],unit:["Nieuwe trainingsunit","New training unit","Neue Trainingseinheit"],equipment:["Apparatuur","Equipment","Ausruestung"],days:["Beschikbare dagen","Available days","Verfuegbare Tage"],favorites:["Favoriete oefeningen","Favorite exercises","Lieblingsuebungen"],excluded:["Uitgesloten oefeningen","Excluded exercises","Ausgeschlossene Uebungen"],health:["Gezondheidscontext","Health context","Gesundheitskontext"],consent:["Toestemming","Consent","Einwilligung"]};
const values={fitness:["Algemene fitness","General fitness","Allgemeine Fitness"],muscle:["Spieropbouw","Muscle building","Muskelaufbau"],strength:["Kracht","Strength","Kraft"],beginner:["Beginner","Beginner","Anfaenger"],experienced:["Ervaren","Experienced","Erfahren"],main:["Hoofdoefening","Main exercise","Hauptuebung"],support:["Ondersteunend","Supporting","Ergaenzend"],compound:["Samengesteld","Compound","Mehrgelenkig"],accessory:["Aanvullend","Accessory","Ergaenzung"],mat:["Mat","Mat","Matte"],dumbbell:["Dumbbell","Dumbbell","Kurzhantel"],band:["Elastiek","Band","Band"],true:["Ja","Yes","Ja"],false:["Nee","No","Nein"],none:["Geen gemelde actuele klacht","No reported current complaint","Keine gemeldete aktuelle Beschwerde"],current:["Actuele klacht","Current complaint","Aktuelle Beschwerde"],recurring:["Terugkerende klacht","Recurring complaint","Wiederkehrende Beschwerde"],unclassified:["Oningedeelde klacht","Unclassified complaint","Nicht eingeordnete Beschwerde"],self_reported:["Zelf gemeld herstel","Self-reported recovery","Selbstberichtete Erholung"],expired_context:["Verlopen context","Expired context","Abgelaufener Kontext"],technical:["Technische onzekerheid","Technical uncertainty","Technische Unsicherheit"],
 mon:["Maandag","Monday","Montag"],tue:["Dinsdag","Tuesday","Dienstag"],wed:["Woensdag","Wednesday","Mittwoch"],thu:["Donderdag","Thursday","Donnerstag"],fri:["Vrijdag","Friday","Freitag"],sat:["Zaterdag","Saturday","Samstag"],sun:["Zondag","Sunday","Sonntag"]};
const errors={intake:["Verplichte intake ontbreekt of is tegenstrijdig.","Required intake missing or conflicting.","Pflichtangaben fehlen oder widersprechen sich."],source:["Bronversie ontbreekt, is ongeldig of verlopen.","Source version missing, invalid or expired.","Quellversion fehlt, ist ungueltig oder abgelaufen."],rule:["Ongeldige regelinhoud.","Invalid rule content.","Ungueltiger Regelinhalt."],rule_missing:["Geen passende regel; geen voorstel.","No matching rule; no proposal.","Keine passende Regel; kein Vorschlag."],rule_conflict:["Meerdere passende regels zonder voorrang; geen voorstel.","Multiple matching rules without precedence; no proposal.","Mehrere passende Regeln ohne Vorrang; kein Vorschlag."],range:["Buiten het toegestane bereik of de vastgelegde stap.","Outside allowed range or defined step.","Ausserhalb des Bereichs oder der festgelegten Schrittweite."],time_budget:["Deze bewerking overschrijdt het beschikbare tijdsbudget.","This edit exceeds the available time budget.","Diese Aenderung ueberschreitet das Zeitbudget."],safety:["Klacht of onvoldoende herstelcontext: geen fysieke planvorming.","Complaint or insufficient recovery context: no physical plan.","Beschwerde oder unzureichender Erholungskontext: kein physischer Plan."],consent:["Toestemming ontbreekt of is ingetrokken. Geen nieuwe verwerking.","Consent missing or withdrawn. No new processing.","Einwilligung fehlt oder wurde widerrufen. Keine neue Verarbeitung."],equipment:["Geen toegestane oefening voor deze apparatuur en uitsluitingen.","No allowed exercise for this equipment and exclusions.","Keine erlaubte Uebung fuer diese Ausruestung und Ausschluesse."],excluded:["Deze oefening is niet toegestaan binnen de actuele regel.","Exercise not allowed under the current rule.","Uebung nach aktueller Regel nicht erlaubt."],day:["Dag niet beschikbaar of al in gebruik.","Day unavailable or already used.","Tag nicht verfuegbar oder bereits belegt."],history:["Historische gegevens niet betrouwbaar gekoppeld; geen voorstel.","History not reliably linked; no proposal.","Historische Daten nicht zuverlaessig verknuepft; kein Vorschlag."],history_conflict:["Tegenstrijdige historische bronnen.","Conflicting historical sources.","Widerspruechliche historische Quellen."],version_conflict:["Oude of dubbele aanvraag; niets gewijzigd.","Stale or duplicate request; nothing changed.","Veraltete oder doppelte Anfrage; nichts geaendert."],idempotent:["Reeds verwerkt; geen extra versie.","Already processed; no extra version.","Bereits verarbeitet; keine weitere Version."],effort:["RIR/RPE past niet bij de afzonderlijke keuze of regel.","RIR/RPE does not match its separate choice or rule.","RIR/RPE entspricht nicht der getrennten Auswahl oder Regel."],plan_source:["Oud plan past niet bij huidige bronnen; opnieuw beoordelen.","Old plan does not match current sources; reassess.","Alter Plan passt nicht zu aktuellen Quellen; neu bewerten."]};
const api={w,labels,values,errors};if(typeof module==="object")module.exports=api;else root.FMZ16Copy=api;
})(globalThis);
