globalThis.FMZ6E12Copy={
  "nl": {
    "weightStep": "Ingestelde gewichtsstap",
    "weights": "Brongewichten",
    "w2Reason": "De lijst met brongewichten past niet bij de ingestelde stap. Geen afronding, kleinere stap of alternatief reps-voorstel.",
    "restoreReason": "Eerdere schema-inhoud herstellen als nieuwe versie. Lid en trainer moeten opnieuw afzonderlijk akkoord geven; daarna blijft apart toepassen verplicht.",
    "title": "Workoutreflectie",
    "demo": "SYNTHETISCH / OFFLINE",
    "scope": "6E-12 testdemo - geen echte accounts of schemawijzigingen",
    "resetNote": "Uitsluitend fictieve gegevens. Alleen geheugenopslag: verversen reset deze demo. Rolkeuze is een simulatie, geen inlog of bevoegdheid.",
    "language": "Taal",
    "theme": "Thema",
    "reset": "Nieuwe demo",
    "scenario": "Synthetisch voorbeeld",
    "role": "Fictieve rol",
    "member": "Lid",
    "trainer": "Trainer",
    "registrationTitle": "Workoutregistratie",
    "register": "Registratie vastleggen",
    "reflect": "Workoutreflectie maken",
    "reviewTitle": "Voorstel en beoordeling",
    "regHistory": "Registratieversies",
    "reasons": "Exact antwoord en bronverwijzingen",
    "history": "Schemaversies",
    "audit": "Gesimuleerde audit",
    "event": "Bronwijziging simuleren",
    "inject": "Wijziging simuleren",
    "empty": "Nog geen reflectie.",
    "current": "Huidig plandoel",
    "next": "Voorstel volgende week",
    "recorded": "Geregistreerd",
    "sets": "sets",
    "reps": "reps",
    "missing": "ontbreekt",
    "restore": "Terugzetten voorstellen",
    "version": "Versie",
    "snapshot": "Historische snapshot",
    "goal": "Doel",
    "exampleLimit": "Deze publieke demo bevat 18 vooraf doorgerekende voorbeelden. Andere invoer levert alleen feiten, geen nieuw berekend voorstel. De volledige validator draait uitsluitend offline.",
    "footer": "Concept voor ownerreview. Geen medische geschiktheid of vrijgave. Geen live AI, accounttoegang, opslag of automatische uitvoering. Ticket SU-487979 blokkeert de echte serverintegratie.",
    "steps": [
      "Registreren",
      "Reflecteren",
      "Lid",
      "Trainer",
      "Toepassen"
    ],
    "states": {
      "member_pending": "Wacht op lidacceptatie",
      "trainer_pending": "Wacht op trainergoedkeuring",
      "approved": "Goedgekeurd - nog niet toegepast",
      "applied": "Nieuwe schemaversie toegepast (simulatie)",
      "maintained": "Bestaand doel behouden",
      "blocked": "Geen toepasbaar voorstel",
      "rejected": "Voorstel afgewezen"
    },
    "actions": {
      "member_accept": "Accepteren",
      "member_reject": "Afwijzen",
      "trainer_approve": "Goedkeuren",
      "trainer_reject": "Afwijzen",
      "trainer_block": "Blokkeren",
      "apply": "Wijziging toepassen"
    },
    "events": {
      "version_conflict": "Nieuwe bronversie",
      "consent_revoked": "Toestemming ingetrokken",
      "relation_revoked": "Trainerkoppeling ingetrokken",
      "expired": "Testtoegang verlopen"
    },
    "feedback": {
      "registration_saved": "Registratie vastgelegd. Een eerdere beoordeling is niet herbruikbaar.",
      "reflection_ready": "Reflectie beschikbaar; er is niets toegepast.",
      "existing_reflection": "De bestaande reflectie blijft behouden.",
      "registration_required": "Er is nog geen registratie.",
      "reflection_required": "Maak eerst een nieuwe reflectie op deze registratie.",
      "not_example": "Deze invoer is niet vooraf doorgerekend: alleen feiten, geen wijzigingsvoorstel.",
      "source_changed": "De bron is gewijzigd; nieuwe bronvalidatie is nodig.",
      "new_plan_source_required": "Na toepassing is een nieuwe geldige plan- en trainerbron nodig. Start een nieuwe synthetische demo.",
      "registration_binding": "De registratie hoort niet bij deze bron.",
      "set_value": "Controleer de waarden. Leeg is onbekend; RIR 0 is geldig, RPE 0 niet.",
      "blocked": "Deze situatie levert geen toepasbare wijziging op.",
      "done": "Gesimuleerde actie verwerkt.",
      "failed": "Actie geweigerd; het schema is niet gewijzigd."
    },
    "scenarios": [
      "Reps, gewicht en behouden",
      "Zelfde eenheid: lb",
      "Doelen behouden",
      "Oefeningstype-regel",
      "RIR 0 in historie",
      "RIR/RPE leeg",
      "Ontbrekende set",
      "Ontbrekende trainerregel",
      "W1: meerdere regels",
      "W2: gewichtsstap past niet",
      "Geen trainer",
      "Actuele klacht",
      "Zelf gemeld herstel",
      "Veiligheidsregistratie verlopen",
      "Broncontext ontbreekt",
      "Geen analysetoestemming",
      "Trainerregel verlopen",
      "Verouderde aanvraag"
    ]
  },
  "en": {
    "weightStep": "Configured weight step",
    "weights": "Source weights",
    "w2Reason": "The source weight list does not match the configured step. No rounding, smaller step or alternative rep proposal.",
    "restoreReason": "Restore previous plan content as a new version. Member and trainer must approve again separately, followed by explicit application.",
    "title": "Workout reflection",
    "demo": "SYNTHETIC / OFFLINE",
    "scope": "6E-12 test demo - no real accounts or plan changes",
    "resetNote": "Fictional data only. Memory only: refreshing resets this demo. Role selection is a simulation, not login or authority.",
    "language": "Language",
    "theme": "Theme",
    "reset": "New demo",
    "scenario": "Synthetic example",
    "role": "Fictional role",
    "member": "Member",
    "trainer": "Trainer",
    "registrationTitle": "Workout record",
    "register": "Record workout",
    "reflect": "Create workout reflection",
    "reviewTitle": "Proposal and review",
    "regHistory": "Record versions",
    "reasons": "Exact response and sources",
    "history": "Plan versions",
    "audit": "Simulated audit",
    "event": "Simulated source event",
    "inject": "Simulate change",
    "empty": "No reflection yet.",
    "current": "Current plan target",
    "next": "Next week's proposal",
    "recorded": "Recorded",
    "sets": "sets",
    "reps": "reps",
    "missing": "missing",
    "restore": "Propose restore",
    "version": "Version",
    "snapshot": "Historical snapshot",
    "goal": "Goal",
    "exampleLimit": "This public demo contains 18 pre-evaluated examples. Other input produces facts only, not a newly calculated proposal. The full validator runs offline only.",
    "footer": "Concept for owner review. No assessment of medical fitness or clearance. No live AI, account access, storage or automatic execution. SU-487979 blocks the real server integration.",
    "steps": [
      "Record",
      "Reflect",
      "Member",
      "Trainer",
      "Apply"
    ],
    "states": {
      "member_pending": "Member acceptance pending",
      "trainer_pending": "Trainer approval pending",
      "approved": "Approved - not yet applied",
      "applied": "New plan version applied (simulation)",
      "maintained": "Keep current target",
      "blocked": "No applicable proposal",
      "rejected": "Proposal rejected"
    },
    "actions": {
      "member_accept": "Accept",
      "member_reject": "Reject",
      "trainer_approve": "Approve",
      "trainer_reject": "Reject",
      "trainer_block": "Block",
      "apply": "Apply change"
    },
    "events": {
      "version_conflict": "New source version",
      "consent_revoked": "Consent revoked",
      "relation_revoked": "Trainer relationship revoked",
      "expired": "Test access expired"
    },
    "feedback": {
      "registration_saved": "Record saved. Previous approval cannot be reused.",
      "reflection_ready": "Reflection available; nothing has been applied.",
      "existing_reflection": "The existing reflection is preserved.",
      "registration_required": "No record has been saved.",
      "reflection_required": "Create a new reflection for this record first.",
      "not_example": "This input was not pre-evaluated: facts only, no change proposal.",
      "source_changed": "The source changed; fresh validation is required.",
      "new_plan_source_required": "After application, a new valid plan and trainer source is required. Start a new synthetic demo.",
      "registration_binding": "The record does not belong to this source.",
      "set_value": "Check the values. Empty means unknown; RIR 0 is valid, RPE 0 is not.",
      "blocked": "No applicable change is available in this situation.",
      "done": "Simulated action recorded.",
      "failed": "Action denied; the plan was not changed."
    },
    "scenarios": [
      "Reps, weight and maintain",
      "Same unit: lb",
      "Maintain targets",
      "Exercise-type rule",
      "RIR 0 in history",
      "RIR/RPE empty",
      "Missing set",
      "Missing trainer rule",
      "W1: multiple rules",
      "W2: weight step does not fit",
      "No trainer",
      "Current complaint",
      "Self-reported recovery",
      "Safety record expired",
      "Source context missing",
      "No analysis consent",
      "Trainer rule expired",
      "Stale request"
    ]
  },
  "de": {
    "weightStep": "Vorgegebener Gewichtsschritt",
    "weights": "Quellgewichte",
    "w2Reason": "Die Quellgewichte passen nicht zum vorgegebenen Schritt. Keine Rundung, kleinere Stufe oder alternative Wiederholungszahl.",
    "restoreReason": "Frühere Planinhalte als neue Version wiederherstellen. Mitglied und Trainer stimmen erneut getrennt zu; danach ist eine ausdrückliche Anwendung nötig.",
    "title": "Trainingsreflexion",
    "demo": "SYNTHETISCH / OFFLINE",
    "scope": "6E-12 Testdemo - keine echten Konten oder Planänderungen",
    "resetNote": "Nur fiktive Daten. Nur Arbeitsspeicher: Neuladen setzt diese Demo zurück. Die Rollenwahl simuliert eine Rolle, keine Anmeldung oder Befugnis.",
    "language": "Sprache",
    "theme": "Design",
    "reset": "Neue Demo",
    "scenario": "Synthetisches Beispiel",
    "role": "Fiktive Rolle",
    "member": "Mitglied",
    "trainer": "Trainer",
    "registrationTitle": "Trainingsaufzeichnung",
    "register": "Training erfassen",
    "reflect": "Trainingsreflexion erstellen",
    "reviewTitle": "Vorschlag und Prüfung",
    "regHistory": "Aufzeichnungsversionen",
    "reasons": "Genaue Antwort und Quellen",
    "history": "Planversionen",
    "audit": "Simulierter Prüfverlauf",
    "event": "Quellenänderung simulieren",
    "inject": "Änderung simulieren",
    "empty": "Noch keine Reflexion.",
    "current": "Aktuelles Planziel",
    "next": "Vorschlag für nächste Woche",
    "recorded": "Aufgezeichnet",
    "sets": "Sätze",
    "reps": "Wdh.",
    "missing": "fehlt",
    "restore": "Wiederherstellung vorschlagen",
    "version": "Version",
    "snapshot": "Historischer Snapshot",
    "goal": "Ziel",
    "exampleLimit": "Diese öffentliche Demo enthält 18 vorberechnete Beispiele. Andere Eingaben liefern nur Fakten, keinen neu berechneten Vorschlag. Der vollständige Validator läuft nur offline.",
    "footer": "Konzept zur Owner-Prüfung. Keine medizinische Eignung oder Freigabe. Keine Live-KI, Kontozugriffe, Speicherung oder automatischen Aktionen. SU-487979 blockiert die echte Serverintegration.",
    "steps": [
      "Erfassen",
      "Reflexion",
      "Mitglied",
      "Trainer",
      "Anwenden"
    ],
    "states": {
      "member_pending": "Zustimmung des Mitglieds ausstehend",
      "trainer_pending": "Trainerfreigabe ausstehend",
      "approved": "Freigegeben - noch nicht angewendet",
      "applied": "Neue Planversion angewendet (Simulation)",
      "maintained": "Aktuelles Ziel beibehalten",
      "blocked": "Kein anwendbarer Vorschlag",
      "rejected": "Vorschlag abgelehnt"
    },
    "actions": {
      "member_accept": "Zustimmen",
      "member_reject": "Ablehnen",
      "trainer_approve": "Freigeben",
      "trainer_reject": "Ablehnen",
      "trainer_block": "Blockieren",
      "apply": "Änderung anwenden"
    },
    "events": {
      "version_conflict": "Neue Quellenversion",
      "consent_revoked": "Einwilligung widerrufen",
      "relation_revoked": "Trainerzuordnung widerrufen",
      "expired": "Testzugang abgelaufen"
    },
    "feedback": {
      "registration_saved": "Aufzeichnung gespeichert. Frühere Freigaben sind nicht wiederverwendbar.",
      "reflection_ready": "Reflexion verfügbar; nichts wurde angewendet.",
      "existing_reflection": "Die bestehende Reflexion bleibt erhalten.",
      "registration_required": "Noch keine Aufzeichnung gespeichert.",
      "reflection_required": "Zuerst eine neue Reflexion zu dieser Aufzeichnung erstellen.",
      "not_example": "Diese Eingabe wurde nicht vorberechnet: nur Fakten, kein Änderungsvorschlag.",
      "source_changed": "Die Quelle wurde geändert; eine neue Validierung ist nötig.",
      "new_plan_source_required": "Nach Anwendung ist eine neue gültige Plan- und Trainerquelle nötig. Eine neue synthetische Demo starten.",
      "registration_binding": "Die Aufzeichnung gehört nicht zu dieser Quelle.",
      "set_value": "Werte prüfen. Leer bedeutet unbekannt; RIR 0 ist gültig, RPE 0 nicht.",
      "blocked": "In dieser Situation ist keine anwendbare Änderung verfügbar.",
      "done": "Simulierte Aktion erfasst.",
      "failed": "Aktion abgewiesen; der Plan wurde nicht geändert."
    },
    "scenarios": [
      "Wiederholungen, Gewicht, Beibehalten",
      "Gleiche Einheit: lb",
      "Ziele beibehalten",
      "Regel nach Übungstyp",
      "RIR 0 im Verlauf",
      "RIR/RPE leer",
      "Fehlender Satz",
      "Fehlende Trainerregel",
      "W1: mehrere Regeln",
      "W2: Gewichtsschritt passt nicht",
      "Kein Trainer",
      "Aktuelle Beschwerden",
      "Selbst gemeldete Besserung",
      "Sicherheitsvermerk abgelaufen",
      "Quellkontext fehlt",
      "Keine Analyseeinwilligung",
      "Trainerregel abgelaufen",
      "Veraltete Anfrage"
    ]
  }
};
