const fs=require("node:fs"),path=require("node:path"),os=require("node:os"),cp=require("node:child_process"),assert=require("node:assert/strict");
const root=path.resolve(__dirname,"../../.."),work=fs.mkdtempSync(path.join(os.tmpdir(),"fmz6e10-checkout-"));
const run=(cmd,args,cwd)=>{const r=cp.spawnSync(cmd,args,{cwd,encoding:"utf8",windowsHide:true,timeout:600000,maxBuffer:60000000});assert.equal(r.status,0,(r.stdout+r.stderr).slice(-4000));return r.stdout;};
const head=run("git",["rev-parse","HEAD"],root).trim();
run("git",["clone","--config","core.autocrlf=false","--no-hardlinks","--branch","main",root,work],root);
assert.equal(run("git",["rev-parse","HEAD"],work).trim(),head);
assert.equal(run("git",["status","--porcelain"],work).trim(),"");
fs.mkdirSync(path.join(work,"supabase/.temp"),{recursive:true});
console.log("fresh checkout canonical Git bytes");
run(process.execPath,["_offline/phase6e10/test/preserve.cjs","--canonical"],work);
const tap=run(process.execPath,["--test","--test-reporter=tap","_offline/phase6e10/test/edge.test.mjs","_offline/phase6e10/test/scope.test.mjs"],work);
const counts=Object.fromEntries(["tests","pass","fail","skipped"].map(k=>[k,Number(tap.match(new RegExp("^# "+k+" (\\d+)$","m"))?.[1])]));
console.log("fresh checkout local SQL");
run(process.execPath,["_offline/phase6e10/test/local.mjs"],work);
const local=JSON.parse(fs.readFileSync(path.join(work,"supabase/.temp/phase6e10-local.json")));
assert(local.pass);assert.equal(counts.fail,0);assert.equal(counts.tests,10);
assert.equal(run("git",["status","--porcelain"],work).trim(),"");
const out={head,work,pass:true,local_groups:local.checks.length,regressions:counts,canonical_bytes:true,full_supabase_stack:false,auth_stubs:true,cluster_stopped:true,deleted_files:0};
fs.writeFileSync(path.join(root,"supabase/.temp/phase6e10-fresh.json"),JSON.stringify(out,null,2)+"\n");console.log(JSON.stringify(out));
