"use strict";
const t=require("node:test"),a=require("node:assert/strict"),fs=require("node:fs"),p=require("node:path"),crypto=require("node:crypto"),{allowed,server}=require("../serve.cjs");
const root=p.resolve(__dirname,"../../.."),sha=x=>crypto.createHash("sha256").update(x).digest("hex");
t("6E13 20 source hashes frozen",()=>{const e=JSON.parse(fs.readFileSync(p.join(root,"docs/PHASE6E13_FREEZE_EVIDENCE.json")));a.equal(e.sources.length,20);for(const x of e.sources)a.equal(sha(fs.readFileSync(p.join(root,x.file))),x.working_sha256,x.file);});
t("M41 and M42 unchanged",()=>{for(const [f,h]of [["20260924155822_phase6e11_rpc_bridge.sql","4d474becdc5c3a7343562602115f9333b5cffc6bed0c323fca3abc560843af7d"],["20260928120846_phase6e11_request_binding.sql","5eebec968d2dae27d4e1462dbcc9de8d9e5599552ff145ad099e57fffd5f5f7c"]])a.equal(sha(fs.readFileSync(p.join(root,"supabase/migrations",f))),h);});
t("public demo imports no private adapter",()=>{for(const f of ["index.html","app.js","copy.js","model.js","data.js"]){const s=fs.readFileSync(p.join(root,"bounded-adjustments-demo",f),"utf8");a.doesNotMatch(s,/_offline\/|supabase\.co|service_role|sb_secret_|postgres:\/\//);a.doesNotMatch(s,/\b(fetch|XMLHttpRequest|WebSocket|localStorage|sessionStorage|indexedDB)\b/);}});
t("CSP prevents backend and workers",()=>{const s=fs.readFileSync(p.join(root,"bounded-adjustments-demo/index.html"),"utf8");a.match(s,/connect-src 'none'/);a.match(s,/worker-src 'none'/);});
t("server allowlist limited to nine public static assets",()=>{a.equal(allowed.length,9);a(allowed.every(x=>!x.includes("_offline")&&!x.includes("supabase")&&!x.includes("..")));a.equal(typeof server,"function");});
t("generated data only fictional owners and no authority flag",()=>{require("../../../bounded-adjustments-demo/data.js");for(const pack of Object.values(globalThis.FMZ14Data))for(const v of Object.values(pack)){a.equal(v.initial.synthetic_only,true);a.equal(v.initial.automatic_actions_allowed,false);a.equal(v.initial.physical_advice_authorized,false);a.equal(v.initial.provider_calls,0);}});
